const $=sel=>document.querySelector(sel);
const transcript=$('#transcript'),composer=$('#composer'),input=$('#messageInput'),guideStrip=$('#guideStrip'),statusPill=$('#statusPill');
const tpl=$('#messageTemplate');
let activeGuide='weaveling';
let tinyPipeline=null;
let tinyLoading=null;

const now=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const clean=(v,max=8000)=>String(v??'').trim().slice(0,max);
const parse=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}};
const read=(key,f)=>parse(localStorage.getItem(key),f);
const write=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v))}catch{}return v};
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const originOf=value=>{try{return new URL(value,location.href).origin}catch{return''}};
const settings=()=>({...{serviceHost:location.origin,aiMode:'auto',hostedPath:'/api/ai/chat',localEndpoint:'',localModel:'',locationPrecisionKm:5,shareValidationSummaries:true,shareCreatorCard:true,validationConfidenceThreshold:.85},...read(KEYS.settings,{})});
const peers=()=>Array.isArray(read(KEYS.peers,[]))?read(KEYS.peers,[]):[];
const records=()=>Array.isArray(read(KEYS.records,[]))?read(KEYS.records,[]):[];
const sessions=()=>{try{return parse(sessionStorage.getItem(KEYS.sessions),{})||{}}catch{return{}}};
const saveSessions=v=>{try{sessionStorage.setItem(KEYS.sessions,JSON.stringify(v))}catch{}return v};
