function passportCard(){const plan=activeWeave();if(!plan)return card('Passport','<p>Create a weave first.</p>');return card('Anarchadia Passport seal',`<p>${escapeHtml(plan.wish||plan.title)}</p><label><span>Personal pledge</span><textarea data-field="pledge">${escapeHtml(plan.passport?.pledge||'I will keep this intention revisable, respect consent, and record what changes.')}</textarea></label><label class="row"><input data-field="confirmPassport" type="checkbox"> I choose to seal this intention in my local Passport record.</label><div class="row">${button('passport:seal','Seal intention','class="primary"')}</div>`)}
function buildWeave(wish,{outcome='',constraints='',posture='practice',level=2}={}){
  const plan={id:uid('weave'),title:clean(wish,90),wish:clean(wish,1000),clarification:{outcome:clean(outcome,1200),constraints:clean(constraints,2000)},skill:{posture:clean(posture,40)||'practice',level:Math.max(0,Math.min(5,Number(level)||0))},state:'review',updatedAt:now(),paths:[
    {id:uid('path'),system:'living-school',guide:'Moss',label:'Learning path',purpose:`Learn what is required to make “${clean(wish,160)}” real.`,state:'review'},
    {id:uid('path'),system:'cerbanimo',guide:'Kamiya',label:'Skilled work path',purpose:`Turn “${clean(wish,160)}” into reviewable work and evidence.`,state:'review'},
    {id:uid('path'),system:'fellowfare',guide:'Rook',label:'Materials & services path',purpose:`Find resources, collaborators, services, or exchange needed for “${clean(wish,160)}”.`,state:'review'}
  ],governance:{guide:'Merlin',state:'review',purpose:'Consent, roles, validation rules, and consequential-action review.'}};
  write(KEYS.working,{stage:'review',plan,updatedAt:now()});return plan;
}
function activateWeave(){const state=read(KEYS.working,{}),plan=state.plan;if(!plan)return null;plan.state='active';plan.updatedAt=now();write(KEYS.working,{...state,stage:'active',plan,updatedAt:now()});const inbox=read(KEYS.inbox,[]);for(const p of plan.paths)inbox.unshift({id:uid('handoff'),target:p.system,status:'review',createdAt:now(),payload:{wish:plan.wish,path:p}});inbox.unshift({id:uid('handoff'),target:'anarchadia',status:'review',createdAt:now(),payload:{wish:plan.wish,governance:plan.governance}});write(KEYS.inbox,inbox.slice(0,200));return plan;}

const RECORD_CONFIG={
  learn:{guide:'moss',title:'Learning',kind:'learning',fields:['title','goal','evidence','status']},
  work:{guide:'kamiya',title:'Work',kind:'work',fields:['title','deliverable','evidence','status']},
  market:{guide:'rook',title:'Market / exchange',kind:'market',fields:['title','needOrOffer','terms','status']},
  govern:{guide:'merlin',title:'Governance',kind:'governance',fields:['title','proposal','consent','status']}
};
function recordTool(id){const c=RECORD_CONFIG[id],items=records().filter(r=>r.kind===c.kind).slice(0,6);return card(c.title,`<p>${id==='learn'?'Track paths, modules, competency and proof.':id==='work'?'Track quests, submissions, validation and settlement.':id==='market'?'Track needs, offers, agreements and service exchange.':'Track proposals, consent, roles, validation and review.'}</p><div class="stack">${items.map(r=>`<div class="creator-preview"><strong>${escapeHtml(r.title||'Untitled')}</strong><p>${escapeHtml(r.summary||r.evidence||r.terms||r.proposal||'')}</p><small>${escapeHtml(r.status||'open')}</small></div>`).join('')||'<small>No records yet.</small>'}</div><div class="row">${button(`record:new:${id}`,'Add record','class="primary"')}</div>`)}
function recordEditor(type){const c=RECORD_CONFIG[type];return card(`New ${c.title.toLowerCase()} record`,`<label><span>Title</span><input data-field="title"></label><label><span>${type==='learn'?'Goal':type==='work'?'Deliverable':type==='market'?'Need or offer':'Proposal'}</span><textarea data-field="body"></textarea></label><label><span>${type==='govern'?'Consent / rule':'Evidence / terms'}</span><textarea data-field="detail"></textarea></label><label><span>Status</span><select data-field="status"><option>draft</option><option>review</option><option>active</option><option>blocked</option><option>complete</option></select></label><div class="row">${button(`record:save:${type}`,'Save','class="primary"')}</div>`)}
function saveRecord(type,root){const c=RECORD_CONFIG[type],title=field(root,'title'),body=field(root,'body'),detail=field(root,'detail'),status=field(root,'status')||'draft';const item={id:uid(c.kind),kind:c.kind,title,summary:body,status,createdAt:now(),updatedAt:now()};if(type==='learn'){item.goal=body;item.evidence=detail}else if(type==='work'){item.deliverable=body;item.evidence=detail}else if(type==='market'){item.needOrOffer=body;item.terms=detail}else{item.proposal=body;item.consent=detail}const all=records();all.unshift(item);write(KEYS.records,all.slice(0,500));return item;}

function rewardWallet(){const r=read(KEYS.rewards,{xp:0,acorns:0,buttons:0});return card('Reward wallet',`<div class="kv"><b>XP</b><span>${Number(r.xp||0)}</span><b>🌰 Acorns</b><span>${Number(r.acorns||0)}</span><b>🔘 Buttons</b><span>${Number(r.buttons||0)}</span></div><small>Cross-device validation remains the payout gate when a reward rule requires it.</small>`)}

async function fetchJson(url,options={}){const response=await fetch(url,{cache:'no-store',...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(clean(body?.error||body?.message,1000)||`${new URL(url,location.href).pathname} returned ${response.status}`);return body;}
function walletCard(){const host=settings().serviceHost||location.origin;return card('AI wallet & node credit',`<p>Uses Civweave-compatible payment surfaces. Node live credit requires pairing first.</p><div class="kv"><b>Service host</b><span>${escapeHtml(originOf(host)||host)}</span></div><div class="row">${button('wallet:plans','Hosted plans')}${button('wallet:node','Paired-node credit')}${button('tool:rewards','Rewards')}</div><div data-wallet-status></div>`)}
async function hostedPlans(root){const target=root.querySelector('[data-wallet-status]');target.textContent='Checking plans…';try{const body=await fetchJson(new URL('/api/ai/plans',settings().serviceHost||location.origin));const plans=Array.isArray(body?.plans)?body.plans:[];target.innerHTML=plans.length?plans.map(p=>`<div class="creator-preview"><strong>${escapeHtml(p.name||p.id)}</strong><p>${escapeHtml(p.description||'')}</p></div>`).join(''):'No hosted plan catalog is enabled on this host.';}catch(e){target.innerHTML=`<span class="error">${escapeHtml(e.message)}</span>`}}
function pairedForPayments(){const s=sessions();return peers().filter(p=>p.paired&&s[p.id]?.token&&p.endpoint)}
async function nodeCreditCard(){const nodes=pairedForPayments();return card('Paired-node live credit',nodes.length?nodes.map(n=>`<div class="creator-preview" data-pay-node="${escapeHtml(n.id)}"><strong>${escapeHtml(n.creator?.displayName||n.name||n.id)}</strong><p>Prepay this node for AI/service credit.</p><label><span>Dollars</span><input type="number" min="1" max="1000" value="5" data-field="amount"></label>${button(`wallet:pay:${n.id}`,'Open secure checkout','class="primary"')}</div>`).join(''):'<p>No payment-ready paired nodes yet.</p>')}
async function payNode(id,root){const peer=peers().find(p=>p.id===id),session=sessions()[id];if(!peer?.endpoint||!session?.token)throw new Error('Pair with this node before adding credit.');const holder=root.closest('[data-pay-node]')||root;const dollars=Math.max(1,Math.min(1000,Number(field(holder,'amount'))||5));const base=session.baseUrl||peer.endpoint;const body=await fetchJson(new URL('/api/ai/node/live/topups',base),{method:'POST',headers:{authorization:`Bearer ${session.token}`,'content-type':'application/json'},body:JSON.stringify({grossCents:Math.round(dollars*100),idempotencyKey:`chat-live:${crypto.randomUUID?.()||Date.now()}`,successUrl:`${location.origin}${location.pathname}?nodeTopup=success`,cancelUrl:`${location.origin}${location.pathname}?nodeTopup=cancelled`})});const url=clean(body?.checkout?.checkoutUrl);if(!url)throw new Error('The node did not return a checkout URL.');location.assign(url);}

function creator(){return {...{displayName:'Creator',blurb:'',services:[],rate:'',availability:'Open',contact:'',updatedAt:now()},...read(KEYS.creator,{})}}
function creatorEditor(editable=true,peer=null){const c=peer?.creator||creator(),prefix=peer?`Peer · ${escapeHtml(peer.name||peer.id)}`:'Your Creator card';if(!editable)return card(prefix,creatorPreview(c,peer));return card(prefix,`<label><span>Display name</span><input data-field="displayName" value="${escapeHtml(c.displayName||'')}"></label><label><span>Paid services</span><textarea data-field="blurb" maxlength="280" placeholder="Briefly describe what people can hire you for.">${escapeHtml(c.blurb||'')}</textarea></label><label><span>Service tags</span><input data-field="services" value="${escapeHtml((c.services||[]).join(', '))}" placeholder="design, coding, tutoring"></label><div class="split"><label><span>Rate / starting price</span><input data-field="rate" value="${escapeHtml(c.rate||'')}"></label><label><span>Availability</span><input data-field="availability" value="${escapeHtml(c.availability||'Open')}"></label></div><label><span>Contact/action endpoint</span><input data-field="contact" value="${escapeHtml(c.contact||'')}"></label><div class="row">${button('creator:save','Save Creator card','class="primary"')}</div><small>This card is the public service advert included in peer gossip when sharing is enabled.</small>`)}
function creatorPreview(c,peer){return `<div class="creator-preview"><h3>${escapeHtml(c.displayName||peer?.name||'Creator')}</h3><p>${escapeHtml(c.blurb||'No paid services advertised yet.')}</p><div class="services">${(c.services||[]).map(t=>`<span class="chip">${escapeHtml(t)}</span>`).join('')}</div>${c.rate?`<div class="price">${escapeHtml(c.rate)}</div>`:''}<small>${escapeHtml(c.availability||'')} ${c.contact?`· ${escapeHtml(c.contact)}`:''}</small></div>`}
function saveCreator(root){const c={displayName:field(root,'displayName')||'Creator',blurb:field(root,'blurb'),services:field(root,'services').split(',').map(x=>x.trim()).filter(Boolean).slice(0,12),rate:field(root,'rate'),availability:field(root,'availability')||'Open',contact:field(root,'contact'),updatedAt:now()};write(KEYS.creator,c);return c;}

