function deviceId(){let id=read(KEYS.state,{}).deviceId;if(!id){id=`device-${crypto.randomUUID?.()||uid('local')}`;write(KEYS.state,{...read(KEYS.state,{}),deviceId:id})}return id;}

function downloadsCard(){return card('Optional downloads',ADDONS.map(a=>`<div class="creator-preview"><strong>${a.recommended?'★ ':''}${escapeHtml(a.name)}</strong><p>${escapeHtml(a.description)}</p><small>${escapeHtml(a.modelId)}${a.approxBytes?` · ~${Math.round(a.approxBytes/1024/1024)} MB graph`:''}</small><div class="row">${button(`download:${a.id}`,'Install add-on','class="primary"')}${button(`download:test:${a.id}`,'Test')}</div><div class="progress"><span data-progress="${a.id}"></span></div><small data-download-status="${a.id}">Not loaded in this session.</small></div>`).join('')+`<small>The base app ships no model weights. Browser/model caches are the intended storage-heavy layer.</small>`)}
async function ensureTiny(root){if(tinyPipeline)return tinyPipeline;if(tinyLoading)return tinyLoading;const addon=ADDONS[0],status=root?.querySelector(`[data-download-status="${addon.id}"]`),bar=root?.querySelector(`[data-progress="${addon.id}"]`);tinyLoading=(async()=>{try{if(status)status.textContent='Loading optional runtime…';const mod=await import(addon.runtime);const {pipeline,env}=mod;if(env){env.allowLocalModels=false;env.useBrowserCache=true;}if(status)status.textContent='Downloading tiny model…';let lastError=null;for(const candidate of addon.modelCandidates||[addon.modelId]){try{if(status)status.textContent=`Downloading ${candidate}…`;tinyPipeline=await pipeline('text-generation',candidate,{progress_callback:p=>{if(bar&&Number.isFinite(p?.progress))bar.style.width=`${Math.max(0,Math.min(100,p.progress))}%`;if(status&&p?.file)status.textContent=`${p.status||'loading'} · ${p.file}`;}});break}catch(error){lastError=error}}if(!tinyPipeline)throw lastError||new Error('No SmolLM2 browser package could be loaded.');if(bar)bar.style.width='100%';if(status)status.textContent='Ready for local routing.';return tinyPipeline;}catch(e){if(status)status.innerHTML=`<span class="error">${escapeHtml(e.message)}</span>`;throw e}finally{tinyLoading=null}})();return tinyLoading;}
async function tinyGenerate(prompt,root=null){const pipe=await ensureTiny(root);const out=await pipe(prompt,{max_new_tokens:96,do_sample:false,return_full_text:false});return clean(out?.[0]?.generated_text||out?.generated_text,3000);}

function settingsCard(){const s=settings();return card('Settings',`<label><span>Service host</span><input data-field="serviceHost" value="${escapeHtml(s.serviceHost)}"></label><label><span>AI mode</span><select data-field="aiMode"><option value="auto" ${s.aiMode==='auto'?'selected':''}>Auto</option><option value="hosted" ${s.aiMode==='hosted'?'selected':''}>Hosted/node</option><option value="tiny" ${s.aiMode==='tiny'?'selected':''}>Tiny local add-on</option><option value="deterministic" ${s.aiMode==='deterministic'?'selected':''}>Deterministic floor</option></select></label><label><span>Hosted chat path</span><input data-field="hostedPath" value="${escapeHtml(s.hostedPath)}"></label><label><span>Local API endpoint (optional)</span><input data-field="localEndpoint" value="${escapeHtml(s.localEndpoint)}" placeholder="http://127.0.0.1:11434"></label><label><span>Nearby location precision (km)</span><input data-field="locationPrecisionKm" type="number" min="1" max="100" value="${Number(s.locationPrecisionKm)||5}"></label><label class="row"><input data-field="shareCreatorCard" type="checkbox" ${s.shareCreatorCard?'checked':''}> Share Creator card in paired-peer gossip</label><label class="row"><input data-field="shareValidationSummaries" type="checkbox" ${s.shareValidationSummaries?'checked':''}> Share validation summaries</label><div class="row">${button('settings:save','Save settings','class="primary"')}</div>`)}
function saveSettings(root){const current=settings(),next={...current,serviceHost:field(root,'serviceHost')||location.origin,aiMode:field(root,'aiMode')||'auto',hostedPath:field(root,'hostedPath')||'/api/ai/chat',localEndpoint:field(root,'localEndpoint'),locationPrecisionKm:Number(field(root,'locationPrecisionKm'))||5,shareCreatorCard:Boolean(root.querySelector('[data-field="shareCreatorCard"]')?.checked),shareValidationSummaries:Boolean(root.querySelector('[data-field="shareValidationSummaries"]')?.checked)};write(KEYS.settings,next);return next;}

function recordsCard(){const all=records();return card('Local records',`<div class="kv"><b>Learning</b><span>${all.filter(r=>r.kind==='learning').length}</span><b>Work</b><span>${all.filter(r=>r.kind==='work').length}</span><b>Market</b><span>${all.filter(r=>r.kind==='market').length}</span><b>Governance</b><span>${all.filter(r=>r.kind==='governance').length}</span><b>Peers</b><span>${peers().length}</span></div><div class="row">${button('export:json','Export JSON')}${button('records:clear','Clear local data','class="danger"')}</div>`)}
function exportBackup(){const payload={schema:'civweave.chat.backup.v1',version:VERSION,exportedAt:now(),working:read(KEYS.working,{}),inbox:read(KEYS.inbox,[]),records:records(),rewards:read(KEYS.rewards,{}),creator:creator(),peers:peers(),settings:settings()};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`civweave-chat-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function field(root,name){const el=root.querySelector(`[data-field="${name}"]`);return clean(el?.value,8000)}
function findRoot(target){return target.closest('.message-body')||target.parentElement}

async function openTool(id){const meta=TOOLS.find(x=>x[0]===id),guide=id==='learn'?'moss':id==='work'?'kamiya':id==='market'?'rook':id==='govern'?'merlin':'weaveling';let html='';switch(id){case'tools':html=toolMenu();break;case'wish':html=wishCard();break;case'learn':case'work':case'market':case'govern':html=recordTool(id);break;case'wallet':html=walletCard();break;case'nodes':html=minimapCard();break;case'creator':html=creatorEditor(true);break;case'downloads':html=downloadsCard();break;case'records':html=recordsCard();break;case'settings':html=settingsCard();break;case'export':exportBackup();html=card('Export','<p>Portable backup created.</p>');break;case'rewards':html=rewardWallet();break;default:html=toolMenu();}addMessage({guide,html});}

function deterministicRoute(text){const t=text.toLowerCase();if(/node|peer|pair|nearby|gossip/.test(t))return'nodes';if(/learn|study|course|skill|module|school/.test(t))return'learn';if(/work|task|quest|build|submit|evidence/.test(t))return'work';if(/buy|sell|service|material|market|price|hire/.test(t))return'market';if(/vote|govern|proposal|consent|role|validation|appeal/.test(t))return'govern';if(/wallet|credit|top.?up|payment|balance/.test(t))return'wallet';if(/download|model|local ai/.test(t))return'downloads';if(/setting|host|endpoint|privacy/.test(t))return'settings';if(/wish|intention|want|goal|become true/.test(t))return'wish';return null;}
async function chooseRoute(text){const s=settings();if((s.aiMode==='tiny'||s.aiMode==='auto')&&tinyPipeline){try{const prompt=`Return exactly one route id from: wish, learn, work, market, govern, wallet, nodes, creator, downloads, records, settings, none. User: ${text}`;const out=(await tinyGenerate(prompt)).toLowerCase();const hit=['wish','learn','work','market','govern','wallet','nodes','creator','downloads','records','settings'].find(x=>out.includes(x));if(hit)return hit;}catch{}}
return deterministicRoute(text);}
async function hostedChat(text,guide){const s=settings();if(s.aiMode==='deterministic'||s.aiMode==='tiny')return null;const host=s.serviceHost||location.origin,path=s.hostedPath||'/api/ai/chat';try{const body=await fetchJson(new URL(path,host),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,guide,persona:{...GUIDES[guide],prompt:GUIDES[guide].prompt},context:{activeWeave:activeWeave(),validationSummary:validationSummary()}})});return clean(body?.text||body?.message||body?.output||body?.response,4000)||null;}catch{return null;}}
async function replyTo(text){setStatus('thinking');const guide=activeGuide;const hosted=await hostedChat(text,guide);if(hosted){addMessage({guide,text:hosted});setStatus('online');return}if((settings().aiMode==='tiny'||settings().aiMode==='auto')&&tinyPipeline){try{const g=GUIDES[guide],out=await tinyGenerate(`${g.prompt}\nAnswer briefly and concretely as ${g.name}. User: ${text}`);if(out){addMessage({guide,text:out});setStatus('local AI');return}}catch{}}
const route=await chooseRoute(text);if(route){addMessage({guide:'weaveling',html:`<p>I routed that to the smallest useful tool surface.</p>${route==='wish'?wishCard():route==='learn'||route==='work'||route==='market'||route==='govern'?recordTool(route):route==='wallet'?walletCard():route==='nodes'?minimapCard():route==='creator'?creatorEditor(true):route==='downloads'?downloadsCard():route==='records'?recordsCard():settingsCard()}`});}else addMessage({guide,html:`<p>I can keep this conversational, but the deterministic floor does not infer a specific tool from that message.</p><div class="row">${button('tool:tools','Show tools')}${button('tool:downloads','Install tiny router LM')}</div>`});setStatus(tinyPipeline?'local AI':'local');}

