function haversineKm(a,b){const R=6371,toRad=d=>d*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),lat1=toRad(a.lat),lat2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function bearing(a,b){const toRad=d=>d*Math.PI/180,toDeg=r=>r*180/Math.PI,lat1=toRad(a.lat),lat2=toRad(b.lat),dLon=toRad(b.lon-a.lon);return (toDeg(Math.atan2(Math.sin(dLon)*Math.cos(lat2),Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(dLon)))+360)%360;}
function minimapCard(){return card('Nearby node radar',`<p>No road tiles, labels, or atlas. Just nearby peers.</p><div class="row">${button('nodes:locate','Use my location','class="primary"')}${button('nodes:refresh','Refresh peers')}${button('nodes:add','Add endpoint')}</div><div data-node-map>${renderMinimap(null)}</div><small>Location stays local unless a configured node-discovery endpoint explicitly receives a coarse query.</small>`)}
function renderMinimap(self){const rows=peers().filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));const radius=Math.max(1,Number(read(KEYS.state,{}).nodeRadiusKm||50));let dots='';if(self){for(const p of rows){const d=haversineKm(self,p);if(d>radius)continue;const angle=(bearing(self,p)-90)*Math.PI/180,r=Math.min(.46,(d/radius)*.46),x=50+Math.cos(angle)*r*100,y=50+Math.sin(angle)*r*100;dots+=`<button class="node-dot ${p.paired?'paired':''}" style="left:${x}%;top:${y}%" title="${escapeHtml(p.name||p.id)} · ${d.toFixed(1)} km" data-action="node:open:${escapeHtml(p.id)}"></button>`}dots+=`<span class="node-dot self" style="left:50%;top:50%"></span>`}
return `<div class="minimap">${dots}</div><div class="legend"><span>● you</span><span>● visible</span><span>● paired</span><span>${radius} km radius</span></div>${!self?'<div class="notice">Tap “Use my location” to plot distances locally.</div>':''}`;}
async function locateNodes(root){const holder=root.querySelector('[data-node-map]');if(!navigator.geolocation){holder.innerHTML='<span class="error">Geolocation is unavailable.</span>';return}holder.innerHTML='<div class="notice">Locating…</div>';navigator.geolocation.getCurrentPosition(pos=>{const self={lat:pos.coords.latitude,lon:pos.coords.longitude};write(KEYS.state,{...read(KEYS.state,{}),selfLocation:self});holder.innerHTML=renderMinimap(self);bindMessageActions(holder);},err=>holder.innerHTML=`<span class="error">${escapeHtml(err.message)}</span>`,{enableHighAccuracy:false,maximumAge:300000,timeout:10000});}
async function refreshPeers(root){const s=settings(),host=s.serviceHost||location.origin,self=read(KEYS.state,{}).selfLocation;const holder=root.querySelector('[data-node-map]');if(!self){holder.insertAdjacentHTML('beforeend','<div class="notice">Location is needed before nearby discovery.</div>');return}try{const precision=Math.max(1,Number(s.locationPrecisionKm)||5);const qLat=Math.round(self.lat/(precision/111))*(precision/111),qLon=Math.round(self.lon/(precision/(111*Math.max(.2,Math.cos(self.lat*Math.PI/180)))))*(precision/(111*Math.max(.2,Math.cos(self.lat*Math.PI/180))));const candidates=['/api/mesh/nearby','/api/nodes/nearby'];let body=null;for(const path of candidates){try{body=await fetchJson(new URL(`${path}?lat=${encodeURIComponent(qLat)}&lon=${encodeURIComponent(qLon)}&radiusKm=${encodeURIComponent(read(KEYS.state,{}).nodeRadiusKm||50)}`,host));break}catch{}}
if(body){mergeDiscoveredPeers(body.nodes||body.peers||body.candidates||[]);}holder.innerHTML=renderMinimap(self);bindMessageActions(holder);}catch(e){holder.insertAdjacentHTML('beforeend',`<div class="error">${escapeHtml(e.message)}</div>`);}}
function mergeDiscoveredPeers(rows){const map=new Map(peers().map(p=>[p.id,p]));for(const raw of rows){const id=clean(raw.nodeId||raw.id||raw.name,180);if(!id)continue;const loc=raw.location||raw.publicLocation||{};const lat=Number(raw.lat??loc.lat??loc.latitude),lon=Number(raw.lon??raw.lng??loc.lon??loc.longitude);map.set(id,{...map.get(id),id,name:clean(raw.displayName||raw.name||id,120),endpoint:clean(raw.endpoint||raw.url||raw.endpoints?.baseUrls?.[0],1000),lat:Number.isFinite(lat)?lat:map.get(id)?.lat,lon:Number.isFinite(lon)?lon:map.get(id)?.lon,creator:raw.creator||raw.creatorCard||map.get(id)?.creator||null,validationSummary:raw.validationSummary||map.get(id)?.validationSummary||null,lastSeenAt:now()});}write(KEYS.peers,[...map.values()].slice(0,250));}
function addPeerCard(){return card('Add node endpoint',`<label><span>Node name</span><input data-field="name"></label><label><span>HTTP endpoint</span><input data-field="endpoint" placeholder="https://node.example"></label><div class="split"><label><span>Latitude</span><input data-field="lat" inputmode="decimal"></label><label><span>Longitude</span><input data-field="lon" inputmode="decimal"></label></div><div class="row">${button('node:save','Save node','class="primary"')}</div>`)}
function savePeer(root){const endpoint=field(root,'endpoint'),name=field(root,'name')||originOf(endpoint)||'Node';const id=uid('node');const all=peers();const latRaw=field(root,'lat'),lonRaw=field(root,'lon'),latValue=latRaw===''?null:Number(latRaw),lonValue=lonRaw===''?null:Number(lonRaw);all.unshift({id,name,endpoint:originOf(endpoint)||endpoint,lat:Number.isFinite(latValue)?latValue:null,lon:Number.isFinite(lonValue)?lonValue:null,paired:false,lastSeenAt:now()});write(KEYS.peers,all);return id;}
async function peerCard(id){const p=peers().find(x=>x.id===id);if(!p)return card('Node','<p>Node not found.</p>');let live='';if(p.endpoint){try{const body=await fetchJson(new URL('/api/ai/node/live/status',p.endpoint));live=body?.live?.enabled?' · live payments':''}catch{}}
return card(`${escapeHtml(p.name||p.id)}${live}`,`${creatorPreview(p.creator||{},p)}<div class="kv"><b>Endpoint</b><span>${escapeHtml(p.endpoint||'not advertised')}</span><b>Pairing</b><span>${p.paired?'paired':'not paired'}</span><b>Validation</b><span>${escapeHtml(p.validationSummary?.label||p.validationSummary?.status||'no summary yet')}</span></div><div class="row">${p.paired?button(`node:unpair:${p.id}`,'Unpair','class="danger"'):button(`node:pair:${p.id}`,'Pair','class="primary"')}${button(`node:gossip:${p.id}`,'Exchange gossip',p.paired?'':'disabled')}${p.paired?(sessions()[p.id]?.token?button(`wallet:nodecard:${p.id}`,'Add credit'):button(`wallet:session:${p.id}`,'Add wallet session')):''}</div><small>Pairing authorizes signed peer exchange according to the local sharing settings. It does not automatically spend money or accept work.</small>`)}
async function pairPeer(id){const all=peers(),p=all.find(x=>x.id===id);if(!p)throw new Error('Node not found.');p.paired=true;p.pairedAt=now();write(KEYS.peers,all);if(globalThis.CivweaveChatMesh)await globalThis.CivweaveChatMesh.savePeer({id:p.id,name:p.name,endpoint:p.endpoint,status:'paired',creator:p.creator||null,validationSummary:p.validationSummary||null});return p;}
async function unpairPeer(id){const all=peers(),p=all.find(x=>x.id===id);if(p){p.paired=false;delete p.pairedAt;write(KEYS.peers,all)}if(globalThis.CivweaveChatMesh)await globalThis.CivweaveChatMesh.removePeer(id);const s=sessions();delete s[id];saveSessions(s);}
async function gossipPeer(id){const p=peers().find(x=>x.id===id);if(!p?.paired)throw new Error('Pair first.');const knownPeers=peers().filter(x=>x.paired).slice(0,32).map(x=>({id:x.id,name:x.name,endpoint:x.endpoint,lat:x.lat,lon:x.lon,creator:x.creator||null,validationSummary:x.validationSummary||null}));const creatorCard=settings().shareCreatorCard?creator():null,summary=settings().shareValidationSummaries?validationSummary():null;if(!globalThis.CivweaveChatMesh)throw new Error('Signed mesh is unavailable in this browser.');const object=await globalThis.CivweaveChatMesh.publishPeerGossip(p,{creatorCard,validationSummary:summary,knownPeers});let sync={sent:0,received:0};if(p.endpoint)sync=await globalThis.CivweaveChatMesh.syncGateway(p.endpoint);const incoming=await globalThis.CivweaveChatMesh.receivedGossip();for(const row of incoming){const payload=row.payload||{};mergeDiscoveredPeers(payload.knownPeers||[]);const sourceId=row.origin?.nodeId;if(sourceId){const all=peers(),match=all.find(x=>x.id===sourceId);if(match){if(payload.creatorCard)match.creator=payload.creatorCard;if(payload.validationSummary)match.validationSummary=payload.validationSummary;match.lastGossipAt=now();write(KEYS.peers,all)}}}p.lastGossipAt=now();write(KEYS.peers,peers().map(x=>x.id===p.id?p:x));return{object,sync,creatorCard,validationSummary:summary,knownPeers};}
function walletSessionCard(id){const p=peers().find(x=>x.id===id);return card('Node wallet session',`<p>${escapeHtml(p?.name||id)} uses a device-bound node wallet session for live top-ups.</p><label><span>Session token</span><textarea data-field="sessionToken" placeholder="Paste node-issued wallet session token"></textarea></label><div class="row">${button(`wallet:sessionsave:${id}`,'Use for this session','class="primary"')}</div><small>Stored in sessionStorage only and cleared when the browser session ends.</small>`)}
function saveWalletSession(id,root){const token=field(root,'sessionToken');if(!token)throw new Error('Paste a node-issued wallet session token.');const p=peers().find(x=>x.id===id);const s=sessions();s[id]={token,baseUrl:p?.endpoint||location.origin};saveSessions(s);return true}
function validationSummary(){const all=records(),complete=all.filter(r=>r.status==='complete').length,review=all.filter(r=>r.status==='review').length;return{schema:'civweave.chat.validation-summary.v1',complete,review,updatedAt:now(),label:`${complete} complete · ${review} review`};}
