'use strict';

const CONNECT_STATE_KEY='civweave.chat.connect.v1';
const CONNECT_INBOX_KEY='civweave.chat.agreement-inbox.v1';
function connectState(){return read(CONNECT_STATE_KEY,{accountId:'',email:'',country:'US',entityType:'individual',status:'not-started',ready:false,updatedAt:null})||{}}
function saveConnectState(patch){const next={...connectState(),...patch,updatedAt:now()};write(CONNECT_STATE_KEY,next);return next}
function agreementInbox(){const rows=read(CONNECT_INBOX_KEY,[]);return Array.isArray(rows)?rows:[]}
function saveAgreementInbox(rows){write(CONNECT_INBOX_KEY,rows.slice(0,100));return rows}
function connectApi(path){return new URL(`/api/connect/${path}`,settings().serviceHost||location.origin)}
function secureStripeConnectUrl(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.hostname!=='connect.stripe.com')throw new Error('Refusing a non-Stripe Connect onboarding URL.');return u.href}
async function creatorMeshId(){if(!globalThis.CivweaveChatMesh)throw new Error('Signed mesh is unavailable.');return globalThis.CivweaveChatMesh.deviceId()}
async function refreshCreatorConnectStatus(accountIdOverride=''){const state=connectState(),accountId=clean(accountIdOverride||state.accountId,220);if(!accountId)return saveConnectState({status:'not-started',ready:false});const meshId=await creatorMeshId(),u=connectApi('status');u.searchParams.set('accountId',accountId);u.searchParams.set('creatorNodeId',meshId);const body=await fetchJson(u),next=saveConnectState({accountId,status:body.status||'pending',ready:Boolean(body.ready),dashboard:body.dashboard||'express',transferStatus:body.transferStatus||'pending'});audit('connect.status',{ready:next.ready,status:next.status});return next}
async function startCreatorOnboarding(root){
  const email=field(root,'connectEmail')||connectState().email,country=(field(root,'connectCountry')||connectState().country||'US').toUpperCase(),entityType=field(root,'connectEntityType')||connectState().entityType||'individual';if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('A payout contact email is required.');if(!/^[A-Z]{2}$/.test(country))throw new Error('Use a two-letter country code.');if(!['individual','company','non_profit','government_entity'].includes(entityType))throw new Error('Choose a supported Creator entity type.');
  const meshId=await creatorMeshId(),body=await fetchJson(connectApi('onboarding'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schema:'civweave.connect-onboarding-request.v1',creatorNodeId:meshId,accountId:connectState().accountId||'',displayName:creator().displayName||'Creator',contactEmail:email,country,entityType,currency:settings().currency})});
  saveConnectState({accountId:body.accountId,email,country,entityType,status:body.status||'onboarding',ready:Boolean(body.ready)});audit('connect.onboarding.started',{accountId:body.accountId});location.assign(secureStripeConnectUrl(body.onboardingUrl));
}
const _creatorBase=creator;
creator=function(){const c=_creatorBase(),cs=connectState();return{...c,payoutReady:Boolean(cs.ready)}};
const _creatorPreviewBase=creatorPreview;
creatorPreview=function(c=creator(),peer=null){const base=_creatorPreviewBase(c,peer),payout=c?.payoutReady?'<span class="chip ok">Stripe payouts ready</span>':'<span class="chip">Payouts not enabled</span>';return `${base}<div class="row">${payout}</div>`};
creatorEditor=function(){const c=creator(),cs=connectState();return card('Creator card',`<label><span>Display name</span><input data-field="displayName" value="${escapeHtml(c.displayName)}"></label><label><span>Paid services</span><textarea data-field="blurb" maxlength="280">${escapeHtml(c.blurb)}</textarea></label><label><span>Service tags</span><input data-field="services" value="${escapeHtml((c.services||[]).join(', '))}"></label><div class="split"><label><span>Rate / starting price</span><input data-field="rate" value="${escapeHtml(c.rate)}"></label><label><span>Availability</span><input data-field="availability" value="${escapeHtml(c.availability)}"></label></div><label><span>Contact/action endpoint</span><input data-field="contact" value="${escapeHtml(c.contact)}"></label><div class="row">${button('creator:save','Save Creator card','class="primary"')}</div><div class="notice"><strong>Stripe Creator payouts</strong><br>${cs.ready?'<span class="success">Recipient onboarding complete.</span>':`Status: ${escapeHtml(cs.status||'not started')}`}<label><span>Payout contact email</span><input data-field="connectEmail" value="${escapeHtml(cs.email||'')}"></label><div class="split"><label><span>Country</span><input data-field="connectCountry" maxlength="2" value="${escapeHtml(cs.country||'US')}"></label><label><span>Entity</span><select data-field="connectEntityType"><option value="individual" ${(cs.entityType||'individual')==='individual'?'selected':''}>Individual</option><option value="company" ${cs.entityType==='company'?'selected':''}>Registered business</option><option value="non_profit" ${cs.entityType==='non_profit'?'selected':''}>Nonprofit</option><option value="government_entity" ${cs.entityType==='government_entity'?'selected':''}>Government entity</option></select></label></div><div class="row">${button('connect:onboard',cs.accountId?'Continue Stripe onboarding':'Enable Creator payouts','class="primary"')}${cs.accountId?button('connect:refresh','Refresh payout status'):''}</div></div><small>The payout account ID is stored only on this device and in the Creator’s signed acceptance of a paid agreement. It is never a Stripe secret.</small>`)};
const _saveCreatorBase=saveCreator;
saveCreator=function(root){const c=_saveCreatorBase(root),email=field(root,'connectEmail'),country=field(root,'connectCountry'),entityType=field(root,'connectEntityType');if(email||country||entityType)saveConnectState({email:email||connectState().email,country:(country||connectState().country||'US').toUpperCase(),entityType:entityType||connectState().entityType||'individual'});return{...c,payoutReady:connectState().ready}};