(()=>{
'use strict';
const DB='civweave-chat-mesh-v1',VERSION=1,CREDENTIAL='device-credential';
const OBJECT_SCHEMA='civweave.community-object.v1';
const encoder=new TextEncoder();
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m);
const now=()=>new Date().toISOString();
const clone=v=>v==null?v:structuredClone(v);
const allowedConsent=new Set(['private','direct','group','public','federated']);
const listeners=new Set();
function emit(type,detail={}){const event={type,detail,at:now()};for(const fn of listeners)try{fn(event)}catch{};dispatchEvent(new CustomEvent('civweave:chat-mesh',{detail:event}));}
function base64url(bytes){let binary='';for(const b of new Uint8Array(bytes))binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromBase64url(value){const raw=String(value).replace(/-/g,'+').replace(/_/g,'/'),padded=raw+'='.repeat((4-raw.length%4)%4),binary=atob(padded);return Uint8Array.from(binary,c=>c.charCodeAt(0))}
function normalized(value){if(Array.isArray(value))return value.map(normalized);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())if(value[key]!==undefined)out[key]=normalized(value[key]);return out}return value}
const canonical=value=>JSON.stringify(normalized(value));
async function sha256(value){return base64url(await crypto.subtle.digest('SHA-256',typeof value==='string'?encoder.encode(value):value))}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('objects')){const s=db.createObjectStore('objects',{keyPath:'id'});s.createIndex('kind','kind');s.createIndex('updatedAt','updatedAt')}if(!db.objectStoreNames.contains('outbox')){const s=db.createObjectStore('outbox',{keyPath:'id'});s.createIndex('status','status')}if(!db.objectStoreNames.contains('peers'))db.createObjectStore('peers',{keyPath:'id'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function tx(stores,mode,work){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(stores,mode),map=Object.fromEntries(stores.map(n=>[n,t.objectStore(n)]));let result;try{result=work(map,t)}catch(e){t.abort();reject(e);return}t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('Mesh transaction aborted'))})}
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
async function credential(){let row=await tx(['meta'],'readonly',s=>req(s.meta.get(CREDENTIAL)));if(row?.privateKey&&row?.publicKey)return row;const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']),publicKey=await crypto.subtle.exportKey('jwk',pair.publicKey),fingerprint=(await sha256(canonical(publicKey))).slice(0,24);row={key:CREDENTIAL,id:`device:${fingerprint}`,fingerprint,publicKey,privateKey:pair.privateKey,createdAt:now()};await tx(['meta'],'readwrite',s=>s.meta.put(row));return row}
const deviceId=async()=> (await credential()).id;
function signable(o){return{schema:o.schema,id:o.id,revision:o.revision,kind:o.kind,purpose:o.purpose,audience:o.audience,consent:o.consent,payload:o.payload,payloadHash:o.payloadHash,parentIds:o.parentIds,createdAt:o.createdAt,updatedAt:o.updatedAt,expiresAt:o.expiresAt,origin:o.origin,hopLimit:o.hopLimit}}
async function sign(key,value){return base64url(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,encoder.encode(canonical(value))))}
async function verify(keyJwk,value,signature){try{const key=await crypto.subtle.importKey('jwk',keyJwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,fromBase64url(signature),encoder.encode(canonical(value)))}catch{return false}}
async function getObject(id){return tx(['objects'],'readonly',s=>req(s.objects.get(id)))}
async function listObjects(){return tx(['objects'],'readonly',s=>req(s.objects.getAll()))}
async function createObject(input={}){const owner=await credential(),consent=allowedConsent.has(input.consent)?input.consent:'private',createdAt=now(),payload=clone(input.payload??{}),previous=input.id?await getObject(input.id).catch(()=>null):null;const o={schema:OBJECT_SCHEMA,id:input.id||`object:${crypto.randomUUID?.()||Date.now()}`,revision:Number(input.revision||previous?.revision+1||1),kind:clean(input.kind||'civweave.record',160),purpose:clean(input.purpose||'local work',500),audience:Array.isArray(input.audience)?[...new Set(input.audience.map(String))].slice(0,100):[],consent,payload,payloadHash:await sha256(canonical(payload)),parentIds:Array.isArray(input.parentIds)?[...new Set(input.parentIds.map(String))].slice(0,50):[],createdAt,updatedAt:createdAt,expiresAt:input.expiresAt||null,origin:{nodeId:owner.id,credential:owner.publicKey,fingerprint:owner.fingerprint},hopLimit:Math.max(0,Math.min(16,Number(input.hopLimit??4))),visited:[owner.id]};o.revisionHash=await sha256(canonical(signable(o)));o.signature=await sign(owner.privateKey,signable(o));await tx(['objects'],'readwrite',s=>s.objects.put(o));if(input.publish!==false&&consent!=='private')await queue(o,input.destinations);emit('object-created',{id:o.id,kind:o.kind,consent});return o}
async function queue(o,destinations=[]){const delivery={id:`delivery:${o.id}:${o.revisionHash}`,objectId:o.id,revisionHash:o.revisionHash,destinations:Array.isArray(destinations)&&destinations.length?destinations:o.audience,status:'pending',attempts:0,createdAt:now(),updatedAt:now(),lastError:null};await tx(['outbox'],'readwrite',s=>s.outbox.put(delivery));return delivery}
async function validateObject(o){if(o?.schema!==OBJECT_SCHEMA||!o.id||!o.revisionHash||!o.signature)return{ok:false,error:'invalid object envelope'};if(await sha256(canonical(o.payload))!==o.payloadHash)return{ok:false,error:'payload hash mismatch'};if(await sha256(canonical(signable(o)))!==o.revisionHash)return{ok:false,error:'revision hash mismatch'};if(!await verify(o.origin?.credential,signable(o),o.signature))return{ok:false,error:'signature rejected'};if(o.expiresAt&&Date.parse(o.expiresAt)<=Date.now())return{ok:false,error:'object expired'};return{ok:true}}
async function ingest(o,context={}){const v=await validateObject(o);if(!v.ok)throw new Error(v.error);const local=await getObject(o.id);if(local?.revisionHash===o.revisionHash)return{status:'duplicate',object:local};if(local&&Number(local.revision)>Number(o.revision))return{status:'older',object:local};const next={...clone(o),visited:[...new Set([...(o.visited||[]),context.fromPeer].filter(Boolean))],receivedAt:now()};await tx(['objects'],'readwrite',s=>s.objects.put(next));emit('object-received',{id:o.id,kind:o.kind,fromPeer:context.fromPeer||null});return{status:'accepted',object:next}}
async function savePeer(peer){const row={...clone(peer),id:clean(peer.id,180),updatedAt:now()};if(!row.id)throw new Error('Peer id is required');await tx(['peers'],'readwrite',s=>s.peers.put(row));emit('peer-saved',{id:row.id});return row}
async function listPeers(){return tx(['peers'],'readonly',s=>req(s.peers.getAll()))}
async function removePeer(id){return tx(['peers'],'readwrite',s=>s.peers.delete(id))}
function intendedFor(o,localId){return o.consent==='public'||o.consent==='federated'||(o.consent==='direct'&&o.audience.includes(localId))}
async function pending(){return tx(['outbox'],'readonly',s=>req(s.outbox.index('status').getAll('pending')))}
async function mark(id,status,error=null){return tx(['outbox'],'readwrite',s=>{const r=s.outbox.get(id);r.onsuccess=()=>{const row=r.result;if(!row)return;row.status=status;row.updatedAt=now();row.attempts=Number(row.attempts||0)+1;row.lastError=error?clean(error,1000):null;s.outbox.put(row)}})}
async function syncGateway(baseUrl){const base=new URL(baseUrl||location.origin),localId=await deviceId(),rows=await pending();let sent=0,received=0;for(const d of rows){const o=await getObject(d.objectId);if(!o)continue;try{const response=await fetch(new URL('/api/envelopes',base),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schema:'civweave.community-object-envelope.v1',from:localId,to:o.audience.length===1?o.audience[0]:'*',kind:'community-object',subject:o.kind,payload:o,correlationId:o.id})});if(!response.ok)throw new Error(`gateway returned ${response.status}`);await mark(d.id,'delivered');sent++;}catch(e){await mark(d.id,'pending',e.message)}}try{const endpoint=new URL('/api/envelopes',base);endpoint.searchParams.set('limit','200');const response=await fetch(endpoint,{cache:'no-store'});if(response.ok){const body=await response.json();for(const env of body.envelopes||[]){if(env.kind!=='community-object'||!env.payload||!intendedFor(env.payload,localId))continue;try{const r=await ingest(env.payload,{fromPeer:env.from});if(r.status==='accepted')received++;}catch{}}}}catch{}emit('gateway-sync',{base:base.origin,sent,received});return{sent,received}}
async function publishPeerGossip(peer,{creatorCard=null,validationSummary=null,knownPeers=[]}={}){const local=await deviceId();const object=await createObject({id:`peer-gossip:${local}:${peer.id}`,kind:'civweave.chat.peer-gossip.v1',purpose:'Share Creator service advert, peer discovery and aggregate validation state with an explicitly paired peer.',consent:'direct',audience:[peer.id],payload:{schema:'civweave.chat.peer-gossip.v1',creatorCard:clone(creatorCard),validationSummary:clone(validationSummary),knownPeers:clone(knownPeers).slice(0,32),sentAt:now()},hopLimit:3,publish:true});return object}
async function receivedGossip(){const local=await deviceId();return (await listObjects()).filter(o=>o.kind==='civweave.chat.peer-gossip.v1'&&o.origin?.nodeId!==local)}
function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
window.CivweaveChatMesh=Object.freeze({OBJECT_SCHEMA,deviceId,credential,createObject,getObject,listObjects,validateObject,ingest,savePeer,listPeers,removePeer,syncGateway,publishPeerGossip,receivedGossip,subscribe});
})();
