const PAYMENT_SESSION_KEY='civweave.chat.stripe-sessions.v1';
async function fetchJson(url,options={}){const timeout=globalThis.AbortSignal?.timeout?AbortSignal.timeout(15000):undefined,response=await fetch(url,{cache:'no-store',credentials:'same-origin',...options,signal:options.signal||timeout}),type=String(response.headers.get('content-type')||'').toLowerCase(),body=type.includes('application/json')?await response.json().catch(()=>({})):{};if(!response.ok)throw new Error(clean(body?.error||body?.message,1000)||`${new URL(url,location.href).pathname} returned ${response.status}`);return body}
function secureCheckoutUrl(raw,base){const u=new URL(raw,base),local=['localhost','127.0.0.1','[::1]'].includes(u.hostname);if(!['http:','https:'].includes(u.protocol)||u.protocol!=='https:'&&!local)throw new Error('Refusing an insecure checkout URL.');return u.href}
function secureStripeCheckoutUrl(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw new Error('Refusing a non-Stripe checkout URL.');return u.href}
function paymentBase(){const path=settings().paymentsPath||'/api/payments',normalized=`${path.replace(/\/+$/,'')}/`;return new URL(normalized,settings().serviceHost||location.origin)}
function paymentAdapter(){return{
  async status(){return fetchJson(new URL('./status',paymentBase()))},
  async createCheckout(request){return fetchJson(new URL('./checkout',paymentBase()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)})},
  async receipt(referenceId,sessionId){const u=new URL('./receipt',paymentBase());u.searchParams.set('referenceId',referenceId);u.searchParams.set('sessionId',sessionId);return fetchJson(u)}
}}
function paymentSessions(){return read(PAYMENT_SESSION_KEY,{})||{}}
function rememberPaymentSession(referenceId,sessionId){const ref=clean(referenceId,180),sid=clean(sessionId,220);if(!ref||!/^cs_[A-Za-z0-9_]+$/.test(sid))return null;const all=paymentSessions();all[ref]={sessionId:sid,updatedAt:now()};write(PAYMENT_SESSION_KEY,all);return sid}
function paymentSessionFor(referenceId){return paymentSessions()?.[referenceId]?.sessionId||''}
const paymentReceipts=()=>Array.isArray(read(KEYS.paymentReceipts,[]))?read(KEYS.paymentReceipts,[]):[];
function paymentReceiptFor(referenceId){return paymentReceipts().find(r=>r.referenceId===referenceId&&r.provider==='stripe')||null}
function storePaymentReceipt(referenceId,raw={}){const all=paymentReceipts(),receipt={schema:'civweave.payment-receipt.v1',referenceId,status:clean(raw.status||raw.state||'unknown',40),provider:clean(raw.provider||'',80),providerReference:clean(raw.providerReference||raw.paymentId||raw.id||'',220),amount:Number(raw.amount??raw.amountPaid??0),currency:clean(raw.currency||settings().currency,12).toUpperCase(),paymentStatus:clean(raw.paymentStatus||'',40),verifiedAt:now()};const i=all.findIndex(r=>r.referenceId===referenceId);if(i>=0)all[i]=receipt;else all.unshift(receipt);write(KEYS.paymentReceipts,all.slice(0,500));audit('payment.receipt.updated',{referenceId,status:receipt.status,provider:receipt.provider});return receipt}
function receiptMatchesAgreement(a,receipt){return Boolean(a&&receipt&&receipt.provider==='stripe'&&receipt.referenceId===a.id&&receipt.status==='paid'&&Math.abs(Number(receipt.amount)-Number(a.amount||0))<.005&&String(receipt.currency||'').toUpperCase()===String(a.currency||settings().currency).toUpperCase())}
function paymentSummary(a,receipt){const matched=receiptMatchesAgreement(a,receipt);return `<div class="kv"><b>Agreement</b><span>${escapeHtml(a.title||a.id)}</span><b>Amount</b><span>${escapeHtml(a.currency||settings().currency)} ${Number(a.amount||0).toFixed(2)}</span><b>Last Stripe check</b><span>${receipt?`${escapeHtml(receipt.status)}${matched?' · amount matched':' · not settlement-ready'}`:Number(a.amount||0)>0?'not checked':'not required'}</span></div><small>Cached receipt data is display-only. Paid settlement performs a fresh Stripe verification and checks reference, amount and currency.</small>`}
async function requestAgreementCheckout(id){const a=getRecord(id);if(!a?.acceptedAt)throw new Error('Accept the agreement before payment.');if(Number(a.amount||0)<=0)throw new Error('This agreement does not require payment.');const request={schema:'civweave.payment-checkout-request.v1',purpose:'fellowfare.exchange',referenceId:a.id,title:clean(a.title||'Civweave agreement',120),amount:Number(a.amount),currency:a.currency||settings().currency};const result=await paymentAdapter().createCheckout(request),raw=result?.checkoutUrl||result?.checkout?.checkoutUrl||result?.url,sessionId=result?.sessionId;if(!raw||!sessionId)throw new Error('Stripe service did not return a Checkout URL and session ID.');rememberPaymentSession(a.id,sessionId);audit('payment.checkout.requested',{referenceId:a.id,provider:'stripe'});location.assign(secureStripeCheckoutUrl(raw))}
async function refreshAgreementReceipt(id,sessionId=''){const sid=rememberPaymentSession(id,sessionId)||paymentSessionFor(id);if(!sid)throw new Error('No Stripe Checkout session is recorded for this agreement.');const raw=await paymentAdapter().receipt(id,sid),receipt=storePaymentReceipt(id,raw?.receipt||raw);return receipt}
async function verifyAgreementPayment(id,sessionId=''){const a=getRecord(id);if(!a?.acceptedAt)throw new Error('Accept the agreement first.');const receipt=await refreshAgreementReceipt(id,sessionId);if(!receiptMatchesAgreement(a,receipt))throw new Error('Stripe has not verified the exact paid amount and currency for this agreement.');return receipt}
async function settlePaidExchange(id){const receipt=await verifyAgreementPayment(id);return settleExchange(id,'paid',receipt)}
async function paymentStatusCard(){let body=null,error='';try{body=await paymentAdapter().status()}catch(e){error=e.message}return card('Stripe payments',`<p>${body?.checkoutEnabled?'<span class="success">Stripe Checkout is configured.</span>':'<span class="warn">Stripe server is reachable but checkout is not configured.</span>'}</p>${body?`<div class="kv"><b>Provider</b><span>${escapeHtml(body.provider||'stripe')}</span><b>API</b><span>${escapeHtml(body.apiVersion||'')}</span><b>Webhook</b><span>${body.webhookConfigured?'signature verification configured':'not configured'}</span></div>`:`<small>${escapeHtml(error||'Start the minimal Stripe server and configure its restricted API key.')}</small>`}<div class="notice"><strong>Server routes</strong><br>GET ${escapeHtml(settings().paymentsPath)}/status<br>POST ${escapeHtml(settings().paymentsPath)}/checkout<br>GET ${escapeHtml(settings().paymentsPath)}/receipt?referenceId=…&amp;sessionId=…<br>POST ${escapeHtml(settings().paymentsPath)}/webhook</div><small>Stripe secrets and webhook verification stay server-side. Checkout uses dynamic payment methods.</small>`)}

function rewardWallet(){statePatch({rewardWalletViewedAt:now()});const r=read(KEYS.rewards,{xp:0,acorns:0,buttons:0}),summary=validationSummary();return card('Reward wallet',`<div class="kv"><b>XP</b><span>${Number(r.xp||0)}</span><b>🌰 Acorns</b><span>${Number(r.acorns||0)}</span><b>🔘 Buttons</b><span>${Number(r.buttons||0)}</span><b>Validation</b><span>${escapeHtml(summary.label)}</span></div><small>Confidence is threshold-based; Button/bonus settlement remains cross-device gated.</small>`)}
function walletCard(){const host=settings().serviceHost||location.origin;return card('Wallet & payments',`<p>Reward balances are local state; FellowFare paid exchange uses Stripe-hosted Checkout with live server verification.</p><div class="kv"><b>Service host</b><span>${escapeHtml(originOf(host)||host)}</span></div><div class="row">${button('tool:rewards','Rewards')}${button('wallet:plans','Hosted AI plans')}${button('wallet:node','Paired-node credit')}${button('wallet:payments','Stripe status')}</div><div data-wallet-status></div>`)}
async function hostedPlans(root){const target=root.querySelector('[data-wallet-status]');target.textContent='Checking plans…';try{const body=await fetchJson(new URL('/api/ai/plans',settings().serviceHost||location.origin)),plans=Array.isArray(body?.plans)?body.plans:[];target.innerHTML=plans.length?plans.map(p=>`<div class="creator-preview"><strong>${escapeHtml(p.name||p.id)}</strong><p>${escapeHtml(p.description||'')}</p></div>`).join(''):'No hosted plan catalog is enabled on this host.'}catch(e){target.innerHTML=`<span class="error">${escapeHtml(e.message)}</span>`}}
function pairedForPayments(){const s=sessions();return peers().filter(p=>p.paired&&s[p.id]?.token&&p.endpoint)}
async function nodeCreditCard(){const nodes=pairedForPayments();return card('Paired-node live credit',nodes.length?nodes.map(n=>`<div class="creator-preview" data-pay-node="${escapeHtml(n.id)}"><strong>${escapeHtml(n.creator?.displayName||n.name||n.id)}</strong><p>Prepay this node for AI/service credit.</p><label><span>Dollars</span><input type="number" min="1" max="1000" value="5" data-field="amount"></label>${button(`wallet:pay:${n.id}`,'Open secure checkout','class="primary"')}</div>`).join(''):'<p>No payment-ready paired nodes yet.</p>')}
async function payNode(id,root){const peer=peers().find(p=>p.id===id),session=sessions()[id];if(!peer?.endpoint||!session?.token)throw new Error('Pair with this node and add its wallet session first.');const holder=root.closest('[data-pay-node]')||root,dollars=Math.max(1,Math.min(1000,Number(field(holder,'amount'))||5)),base=session.baseUrl||peer.endpoint,body=await fetchJson(new URL('/api/ai/node/live/topups',base),{method:'POST',headers:{authorization:`Bearer ${session.token}`,'content-type':'application/json'},body:JSON.stringify({grossCents:Math.round(dollars*100),idempotencyKey:`chat-live:${crypto.randomUUID?.()||Date.now()}`,successUrl:`${location.origin}${location.pathname}?nodeTopup=success`,cancelUrl:`${location.origin}${location.pathname}?nodeTopup=cancelled`})}),raw=clean(body?.checkout?.checkoutUrl);if(!raw)throw new Error('The node did not return a checkout URL.');location.assign(secureCheckoutUrl(raw,base))}
