async function fetchJson(url,options={}){const response=await fetch(url,{cache:'no-store',...options}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(clean(body?.error||body?.message,1000)||`${new URL(url,location.href).pathname} returned ${response.status}`);return body}
function secureCheckoutUrl(raw,base){const u=new URL(raw,base),local=['localhost','127.0.0.1','[::1]'].includes(u.hostname);if(u.protocol!=='https:'&&!local)throw new Error('Refusing an insecure checkout URL.');return u.href}
function paymentBase(){const path=settings().paymentsPath||'/api/payments',normalized=`${path.replace(/\/+$/,'')}/`;return new URL(normalized,settings().serviceHost||location.origin)}
function defaultPaymentAdapter(){return{
  async status(){return fetchJson(new URL('./status',paymentBase()))},
  async createCheckout(request){return fetchJson(new URL('./checkout',paymentBase()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)})},
  async receipt(referenceId){const u=new URL('./receipt',paymentBase());u.searchParams.set('referenceId',referenceId);return fetchJson(u)}
}}
function paymentAdapter(){const a=globalThis.CivweavePayments;return a&&typeof a.createCheckout==='function'?a:defaultPaymentAdapter()}
const paymentReceipts=()=>Array.isArray(read(KEYS.paymentReceipts,[]))?read(KEYS.paymentReceipts,[]):[];
function paymentReceiptFor(referenceId){return paymentReceipts().find(r=>r.referenceId===referenceId&&['paid','settled','complete','succeeded'].includes(String(r.status||'').toLowerCase()))||null}
function storePaymentReceipt(referenceId,raw={}){const all=paymentReceipts(),receipt={schema:'civweave.payment-receipt.v1',referenceId,status:clean(raw.status||raw.state||'unknown',40),provider:clean(raw.provider||'',80),providerReference:clean(raw.providerReference||raw.paymentId||raw.id||'',200),amount:Number(raw.amount??raw.amountPaid??0),currency:clean(raw.currency||settings().currency,12),receivedAt:now(),raw:{id:raw.id||null,status:raw.status||raw.state||null}};const i=all.findIndex(r=>r.referenceId===referenceId);if(i>=0)all[i]=receipt;else all.unshift(receipt);write(KEYS.paymentReceipts,all.slice(0,500));audit('payment.receipt.updated',{referenceId,status:receipt.status});return receipt}
function paymentSummary(a,receipt){return `<div class="kv"><b>Agreement</b><span>${escapeHtml(a.title||a.id)}</span><b>Amount</b><span>${escapeHtml(a.currency||settings().currency)} ${Number(a.amount||0).toFixed(2)}</span><b>Payment</b><span>${receipt?escapeHtml(receipt.status):Number(a.amount||0)>0?'awaiting receipt':'not required'}</span></div><small>The browser never holds processor secrets. It only requests checkout and reads a server-issued receipt.</small>`}
async function requestAgreementCheckout(id){const a=getRecord(id);if(!a?.acceptedAt)throw new Error('Accept the agreement before payment.');if(Number(a.amount||0)<=0)throw new Error('This agreement does not require payment.');const adapter=paymentAdapter(),request={schema:'civweave.payment-checkout-request.v1',purpose:'fellowfare.exchange',referenceId:a.id,amount:Number(a.amount),currency:a.currency||settings().currency,successUrl:`${location.origin}${location.pathname}?payment=success&referenceId=${encodeURIComponent(a.id)}`,cancelUrl:`${location.origin}${location.pathname}?payment=cancelled&referenceId=${encodeURIComponent(a.id)}`,metadata:{agreementId:a.id,threadId:a.threadId||null,counterparty:a.counterparty||null}};const result=await adapter.createCheckout(request),raw=result?.checkoutUrl||result?.checkout?.checkoutUrl||result?.url;if(!raw)throw new Error('Payment service did not return checkoutUrl.');audit('payment.checkout.requested',{referenceId:a.id});location.assign(secureCheckoutUrl(raw,paymentBase()));}
async function refreshAgreementReceipt(id){const raw=await paymentAdapter().receipt(id),receipt=storePaymentReceipt(id,raw?.receipt||raw);return receipt}
async function paymentStatusCard(){let body=null,error='';try{body=await paymentAdapter().status()}catch(e){error=e.message}return card('Payment wiring',`<p>${body?'<span class="success">Payment service reachable.</span>':'<span class="warn">Payment service not wired yet.</span>'}</p>${body?`<div class="kv"><b>Provider</b><span>${escapeHtml(body.provider||'adapter')}</span><b>Checkout</b><span>${body.checkoutEnabled===false?'disabled':'available'}</span></div>`:`<small>${escapeHtml(error||'Implement the HTTP contract or provide window.CivweavePayments.')}</small>`}<div class="notice"><strong>Browser contract</strong><br>GET ${escapeHtml(settings().paymentsPath)}/status<br>POST ${escapeHtml(settings().paymentsPath)}/checkout<br>GET ${escapeHtml(settings().paymentsPath)}/receipt?referenceId=…</div><small>Expected checkout request schema: civweave.payment-checkout-request.v1. Expected receipt schema: civweave.payment-receipt.v1. Secrets, webhook verification and canonical money settlement remain server-side.</small>`)}

function rewardWallet(){statePatch({rewardWalletViewedAt:now()});const r=read(KEYS.rewards,{xp:0,acorns:0,buttons:0}),summary=validationSummary();return card('Reward wallet',`<div class="kv"><b>XP</b><span>${Number(r.xp||0)}</span><b>🌰 Acorns</b><span>${Number(r.acorns||0)}</span><b>🔘 Buttons</b><span>${Number(r.buttons||0)}</span><b>Validation</b><span>${escapeHtml(summary.label)}</span></div><small>Confidence is threshold-based; Button/bonus settlement remains cross-device gated.</small>`)}
function walletCard(){const host=settings().serviceHost||location.origin;return card('Wallet & payments',`<p>Reward balances are local state; paid exchange and node credit use explicit server-side payment contracts.</p><div class="kv"><b>Service host</b><span>${escapeHtml(originOf(host)||host)}</span></div><div class="row">${button('tool:rewards','Rewards')}${button('wallet:plans','Hosted AI plans')}${button('wallet:node','Paired-node credit')}${button('wallet:payments','Payment wiring')}</div><div data-wallet-status></div>`)}
async function hostedPlans(root){const target=root.querySelector('[data-wallet-status]');target.textContent='Checking plans…';try{const body=await fetchJson(new URL('/api/ai/plans',settings().serviceHost||location.origin)),plans=Array.isArray(body?.plans)?body.plans:[];target.innerHTML=plans.length?plans.map(p=>`<div class="creator-preview"><strong>${escapeHtml(p.name||p.id)}</strong><p>${escapeHtml(p.description||'')}</p></div>`).join(''):'No hosted plan catalog is enabled on this host.'}catch(e){target.innerHTML=`<span class="error">${escapeHtml(e.message)}</span>`}}
function pairedForPayments(){const s=sessions();return peers().filter(p=>p.paired&&s[p.id]?.token&&p.endpoint)}
async function nodeCreditCard(){const nodes=pairedForPayments();return card('Paired-node live credit',nodes.length?nodes.map(n=>`<div class="creator-preview" data-pay-node="${escapeHtml(n.id)}"><strong>${escapeHtml(n.creator?.displayName||n.name||n.id)}</strong><p>Prepay this node for AI/service credit.</p><label><span>Dollars</span><input type="number" min="1" max="1000" value="5" data-field="amount"></label>${button(`wallet:pay:${n.id}`,'Open secure checkout','class="primary"')}</div>`).join(''):'<p>No payment-ready paired nodes yet.</p>')}
async function payNode(id,root){const peer=peers().find(p=>p.id===id),session=sessions()[id];if(!peer?.endpoint||!session?.token)throw new Error('Pair with this node and add its wallet session first.');const holder=root.closest('[data-pay-node]')||root,dollars=Math.max(1,Math.min(1000,Number(field(holder,'amount'))||5)),base=session.baseUrl||peer.endpoint,body=await fetchJson(new URL('/api/ai/node/live/topups',base),{method:'POST',headers:{authorization:`Bearer ${session.token}`,'content-type':'application/json'},body:JSON.stringify({grossCents:Math.round(dollars*100),idempotencyKey:`chat-live:${crypto.randomUUID?.()||Date.now()}`,successUrl:`${location.origin}${location.pathname}?nodeTopup=success`,cancelUrl:`${location.origin}${location.pathname}?nodeTopup=cancelled`})}),raw=clean(body?.checkout?.checkoutUrl);if(!raw)throw new Error('The node did not return a checkout URL.');location.assign(secureCheckoutUrl(raw,base))}
