const SYSTEM_EVENT_TYPES=['civweave.intention.created','living-school.learning.verified','living-school.validation.completed','cerbanimo.labor.completed','cerbanimo.task.available','fellowfare.exchange.completed','fellowfare.resource.available','anarchadia.policy.published','anarchadia.passport.updated'];
function updateRecord(id,patch){const r=getRecord(id);if(!r)throw new Error('Record not found.');return upsertRecord({...r,...patch})}
function recordList(kind,subtype=null){return records().filter(r=>r.kind===kind&&(!subtype||r.subtype===subtype))}
function draftSystemEvent(type,source,target,payload={}){if(!SYSTEM_EVENT_TYPES.includes(type))throw new Error('Unknown system event type.');const item={id:uid('draft'),schema:'civweave.system-event-draft/v1',type,source,target,payload,createdAt:now(),status:'draft'};const all=read(KEYS.projections,[]);all.unshift(item);write(KEYS.projections,all.slice(0,500));audit('system.draft.created',{type,source,target});return item}

function learningCard(){const paths=recordList('learning','learning-path');return card('Living School',`<p>Learning paths hold modules, practice notes, quiz/project evidence and competency validation without leaving chat.</p><div class="stack">${paths.map(p=>learningPathPreview(p)).join('')||'<small>No learning path yet. Activate a weave first, or create one below.</small>'}</div><div class="row">${button('learning:new','New learning path')}${button('tool:validate','Validate competency')}</div>`)}
function learningPathPreview(p){const mods=p.modules||[],done=mods.filter(m=>m.status==='complete').length;return `<div class="creator-preview"><strong>${escapeHtml(p.title)}</strong><p>${escapeHtml(p.goal||'')}</p><div class="row"><span class="chip ${p.status==='active'||p.status==='complete'?'ok':'warn'}">${escapeHtml(p.status)}</span><span class="chip">${done}/${mods.length||0} modules</span>${validationBadge(p.id)}</div><div class="row">${p.status==='ready'?button(`learning:start:${p.id}`,'Start path','class="primary"'):''}${button(`learning:open:${p.id}`,'Open')}${p.status==='active'&&!p.questSentAt?button(`learning:sendquest:${p.id}`,'Send quest'):''}</div></div>`}
function learningPathCard(id){const p=getRecord(id);if(!p)return learningCard();const mods=p.modules||[];return card(p.title,`<p>${escapeHtml(p.goal||'')}</p><div class="stack">${mods.map((m,i)=>`<div class="creator-preview"><strong>${i+1}. ${escapeHtml(m.title)}</strong><p>${escapeHtml(m.content||'')}</p><div class="row"><span class="chip ${m.status==='complete'?'ok':'warn'}">${escapeHtml(m.status)}</span>${m.status!=='complete'?button(`learning:module:${p.id}:${m.id}`,'Complete / evidence'):''}</div>${m.evidence?`<small>Evidence: ${escapeHtml(m.evidence)}</small>`:''}</div>`).join('')||'<small>Start the path to generate the first module set.</small>'}</div><div class="row">${p.status==='ready'?button(`learning:start:${p.id}`,'Start path','class="primary"'):''}${p.status==='active'&&!p.questSentAt?button(`learning:sendquest:${p.id}`,'Send work quest'):''}${button(`validation:add:${p.id}`,'Validate path')}</div>`)}
function learningNewCard(){const p=activeWeave();return card('New learning path',`<label><span>Title</span><input data-field="title" value="${escapeHtml(p?`Learning · ${p.title}`:'')}"></label><label><span>Goal</span><textarea data-field="goal">${escapeHtml(p?.paths?.learning||'')}</textarea></label><div class="row">${button('learning:save-new','Save path','class="primary"')}</div>`)}
function startLearning(id){const p=getRecord(id);if(!p)throw new Error('Learning path not found.');const seed=clean(p.goal||p.title,220),mods=(p.modules||[]).length?p.modules:[
  {id:uid('module'),title:'Orient',content:`Define the concepts, constraints and success evidence for ${seed}.`,status:'ready'},
  {id:uid('module'),title:'Practice',content:`Practice the central skill in a small, reviewable attempt connected to ${seed}.`,status:'ready'},
  {id:uid('module'),title:'Demonstrate',content:`Produce evidence that the skill transfers to the active intention.`,status:'ready'}];
  updateRecord(id,{status:'active',startedAt:now(),modules:mods});audit('living-school.path.started',{recordId:id});return getRecord(id)
}
function moduleEvidenceCard(pathId,moduleId){const p=getRecord(pathId),m=p?.modules?.find(x=>x.id===moduleId);if(!m)return learningCard();return card(`Module · ${escapeHtml(m.title)}`,`<p>${escapeHtml(m.content||'')}</p><label><span>Practice / quiz / project evidence</span><textarea data-field="evidence" placeholder="What did you do or learn?"></textarea></label><label><span>Self-check score · 0–100</span><input data-field="score" type="number" min="0" max="100" value="80"></label><label class="row"><input data-field="confirmModule" type="checkbox"> I completed this module and want to record the evidence.</label><div class="row">${button(`learning:module-save:${pathId}:${moduleId}`,'Complete module','class="primary"')}</div>`)}
function completeModule(pathId,moduleId,root){if(!checked(root,'confirmModule'))throw new Error('Confirm the module completion first.');const p=getRecord(pathId);if(!p)throw new Error('Learning path not found.');const mods=(p.modules||[]).map(m=>m.id===moduleId?{...m,status:'complete',evidence:field(root,'evidence'),score:Math.max(0,Math.min(100,Number(field(root,'score'))||0)),completedAt:now()}:m),complete=mods.length&&mods.every(m=>m.status==='complete');updateRecord(pathId,{modules:mods,status:complete?'complete':'active',completedAt:complete?now():p.completedAt});audit('living-school.module.completed',{pathId,moduleId});if(complete)draftSystemEvent('living-school.learning.verified','living-school','civweave',{pathId});return getRecord(pathId)}
function sendLearningQuest(pathId){const p=getRecord(pathId);if(!p)throw new Error('Learning path not found.');let q=records().find(r=>r.kind==='work'&&r.learningPathId===pathId);if(!q)q=newRecord('work','work-quest',{learningPathId:pathId,weaveId:p.weaveId,title:`Quest · ${p.title.replace(/^Learning · /,'')}`,deliverable:`Apply the learning path “${p.title}” to a concrete deliverable.`,evidence:'',status:'queued'});updateRecord(pathId,{questSentAt:now()});draftSystemEvent('cerbanimo.task.available','living-school','cerbanimo',{questId:q.id,learningPathId:pathId});audit('living-school.quest.sent',{pathId,questId:q.id});return q}

function workCard(){const qs=recordList('work','work-quest');return card('Cerbanimo',`<p>Quests move from queued → active → submitted → validated → rewarded. Submission and settlement are explicit.</p><div class="stack">${qs.map(q=>questPreview(q)).join('')||'<small>No quests yet.</small>'}</div><div class="row">${button('work:new','New quest')}${button('tool:validate','Validation')}</div>`)}
function questPreview(q){return `<div class="creator-preview"><strong>${escapeHtml(q.title)}</strong><p>${escapeHtml(q.deliverable||'')}</p><div class="row"><span class="chip ${q.status==='rewarded'?'ok':'warn'}">${escapeHtml(q.status)}</span>${validationBadge(q.id)}</div><div class="row">${button(`work:manage:${q.id}`,'Manage','class="primary"')}${q.submittedAt?button(`work:settle:${q.id}`,'Settle reward'):''}</div></div>`}
function workNewCard(){const p=activeWeave();return card('New quest',`<label><span>Title</span><input data-field="title" value="${escapeHtml(p?`Quest · ${p.title}`:'')}"></label><label><span>Deliverable</span><textarea data-field="deliverable">${escapeHtml(p?.paths?.work||'')}</textarea></label><div class="row">${button('work:save-new','Save quest','class="primary"')}</div>`)}
function questManageCard(id){const q=getRecord(id);if(!q)return workCard();if(!q.managedAt)updateRecord(id,{managedAt:now(),status:q.status==='queued'?'active':q.status});const fresh=getRecord(id);return card(fresh.title,`<p>${escapeHtml(fresh.deliverable||'')}</p>${fresh.evidence?`<div class="notice">Evidence: ${escapeHtml(fresh.evidence)}</div>`:''}<div class="row"><span class="chip">${escapeHtml(fresh.status)}</span>${validationBadge(id)}</div><div class="row">${!fresh.submittedAt?button(`work:submit-card:${id}`,'Submit work','class="primary"'):''}${button(`validation:add:${id}`,'Add validation')}${fresh.submittedAt?button(`work:settle:${id}`,'Settle reward'):''}</div>`)}
function workSubmitCard(id){const q=getRecord(id);if(!q)return workCard();return card(`Submit · ${escapeHtml(q.title)}`,`<label><span>Evidence / artifact reference</span><textarea data-field="evidence">${escapeHtml(q.evidence||'')}</textarea></label><label class="row"><input data-field="confirmSubmit" type="checkbox"> Submit this work for review and validation.</label><div class="row">${button(`work:submit:${id}`,'Submit','class="primary"')}</div>`)}
function submitWork(id,root){if(!checked(root,'confirmSubmit'))throw new Error('Confirm submission first.');const q=updateRecord(id,{evidence:field(root,'evidence'),status:'submitted',submittedAt:now()});audit('cerbanimo.work.submitted',{recordId:id});return q}
function settleReward(id){const q=getRecord(id);if(!q?.submittedAt)throw new Error('Submit work before settlement.');const roll=validationRollup(id);if(!roll.payoutEligible)throw new Error(`Reward is not payout-ready. Confidence: ${roll.status}; cross-device proof: ${roll.crossDevice?'yes':'no'}.`);if(q.rewardSettledAt)return q;const reward=read(KEYS.rewards,{xp:0,acorns:0,buttons:0}),xp=100,acorns=10,buttons=1;write(KEYS.rewards,{xp:Number(reward.xp||0)+xp,acorns:Number(reward.acorns||0)+acorns,buttons:Number(reward.buttons||0)+buttons});updateRecord(id,{status:'rewarded',rewardSettledAt:now(),reward:{xp,acorns,buttons}});draftSystemEvent('cerbanimo.labor.completed','cerbanimo','civweave',{recordId:id,reward:{xp,acorns,buttons}});audit('cerbanimo.reward.settled',{recordId:id,xp,acorns,buttons});return getRecord(id)}

function marketCard(){statePatch({marketBrowsedAt:now()});const threads=recordList('market','market-thread'),agreements=recordList('market','agreement');return card('FellowFare',`<p>Needs, offers and Creator services become reviewable agreements. Payment is requested only after explicit acceptance.</p><h3>Threads</h3><div class="stack">${threads.map(t=>marketThreadPreview(t)).join('')||'<small>No threads yet.</small>'}</div><h3>Agreements</h3><div class="stack">${agreements.map(a=>agreementPreview(a)).join('')||'<small>No agreements yet.</small>'}</div><div class="row">${button('market:new','New thread')}${button('tool:creator','Creator card')}</div>`)}
function marketThreadPreview(t){return `<div class="creator-preview"><strong>${escapeHtml(t.title)}</strong><p>${escapeHtml(t.needOrOffer||'')}</p><small>${escapeHtml(t.currency||settings().currency)} ${Number(t.amount||0).toFixed(2)} · ${escapeHtml(t.status)}</small><div class="row">${button(`market:agreement:${t.id}`,'Draft agreement','class="primary"')}</div></div>`}
function marketNewCard(){return card('New market thread',`<label><span>Need / offer title</span><input data-field="title"></label><label><span>Description</span><textarea data-field="needOrOffer"></textarea></label><div class="split"><label><span>Amount</span><input data-field="amount" type="number" min="0" step="0.01" value="0"></label><label><span>Currency</span><input data-field="currency" value="${escapeHtml(settings().currency)}"></label></div><label><span>Terms / constraints</span><textarea data-field="terms"></textarea></label><div class="row">${button('market:save-new','Publish locally','class="primary"')}</div><small>“Publish” here means create the local thread. Peer/network publication remains a separate consent boundary.</small>`)}
function agreementDraftCard(threadId){const t=getRecord(threadId);if(!t)return marketCard();return card('Draft agreement',`<p>${escapeHtml(t.needOrOffer||'')}</p><label><span>Counterparty / provider</span><input data-field="counterparty" placeholder="Creator or node"></label><label><span>Terms</span><textarea data-field="terms">${escapeHtml(t.terms||'')}</textarea></label><div class="split"><label><span>Amount</span><input data-field="amount" type="number" min="0" step="0.01" value="${Number(t.amount||0)}"></label><label><span>Currency</span><input data-field="currency" value="${escapeHtml(t.currency||settings().currency)}"></label></div><div class="row">${button(`market:agreement-save:${threadId}`,'Create reviewable agreement','class="primary"')}</div>`)}
function agreementPreview(a){return `<div class="creator-preview"><strong>${escapeHtml(a.title)}</strong><p>${escapeHtml(a.terms||'')}</p><div class="row"><span class="chip ${a.settledAt?'ok':'warn'}">${escapeHtml(a.status)}</span><span class="chip">${escapeHtml(a.currency)} ${Number(a.amount||0).toFixed(2)}</span></div><div class="row">${!a.acceptedAt?button(`market:accept-card:${a.id}`,'Review / accept','class="primary"'):button(`market:settle-card:${a.id}`,'Settlement')}</div></div>`}
function acceptAgreementCard(id){const a=getRecord(id);if(!a)return marketCard();return card(`Accept · ${escapeHtml(a.title)}`,`<p>${escapeHtml(a.terms||'')}</p><div class="kv"><b>Amount</b><span>${escapeHtml(a.currency)} ${Number(a.amount||0).toFixed(2)}</span><b>Counterparty</b><span>${escapeHtml(a.counterparty||'unspecified')}</span></div><label class="row"><input data-field="confirmAgreement" type="checkbox"> I accept these terms and understand payment may be requested separately.</label><div class="row">${button(`market:accept:${id}`,'Accept agreement','class="primary"')}</div>`)}
function acceptAgreement(id,root){if(!checked(root,'confirmAgreement'))throw new Error('Confirm agreement acceptance first.');const a=updateRecord(id,{status:'accepted',acceptedAt:now()});audit('fellowfare.agreement.accepted',{recordId:id});return a}
function settlementCard(id){const a=getRecord(id);if(!a)return marketCard();const receipt=paymentReceiptFor(id);return card(`Settle · ${escapeHtml(a.title)}`,`${paymentSummary(a,receipt)}<div class="row">${a.amount>0&&!receipt?button(`payment:checkout:${id}`,'Open payment checkout','class="primary"'):''}${a.amount>0?button(`payment:refresh:${id}`,'Check receipt'):button(`market:settle-manual:${id}`,'Settle zero-cost exchange','class="primary"')}</div>${receipt?`<div class="row">${button(`market:settle-paid:${id}`,'Record exchange settled','class="primary"')}</div>`:''}`)}
function settleExchange(id,mode='paid'){const a=getRecord(id);if(!a?.acceptedAt)throw new Error('Accept the agreement first.');if(Number(a.amount||0)>0&&mode==='paid'&&!paymentReceiptFor(id))throw new Error('No verified payment receipt is available yet.');if(a.settledAt)return a;const next=updateRecord(id,{status:'settled',settledAt:now(),settlementMode:mode});draftSystemEvent('fellowfare.exchange.completed','fellowfare','civweave',{agreementId:id,amount:a.amount,currency:a.currency});audit('fellowfare.exchange.settled',{recordId:id,mode});return next}

function governanceCard(){const rows=recordList('governance');const p=activeWeave();return card('Anarchadia',`${p?`<div class="row">${button('wish:passport','Passport seal')}</div>`:''}<p>Governance records keep proposals, roles, consent decisions, votes and appeals reviewable.</p><div class="stack">${rows.slice(0,12).map(r=>`<div class="creator-preview"><strong>${escapeHtml(r.title)}</strong><p>${escapeHtml(r.proposal||r.note||'')}</p><div class="row"><span class="chip">${escapeHtml(r.subtype||'record')}</span><span class="chip ${r.status==='approved'?'ok':'warn'}">${escapeHtml(r.status)}</span>${button(`govern:open:${r.id}`,'Open')}</div></div>`).join('')||'<small>No governance records yet.</small>'}</div><div class="row">${button('govern:new','New governance record','class="primary"')}</div>`)}
function governanceNewCard(){return card('New governance record',`<label><span>Type</span><select data-field="subtype"><option value="proposal">Proposal</option><option value="role">Role / responsibility</option><option value="consent">Consent decision</option><option value="appeal">Appeal / dispute</option><option value="feature-request">Feature request</option><option value="bug-report">Bug report</option></select></label><label><span>Title</span><input data-field="title"></label><label><span>Proposal / note</span><textarea data-field="proposal"></textarea></label><label><span>Consent level</span><select data-field="consent"><option value="review">Review</option><option value="explicit">Explicit</option><option value="automatic">Automatic</option></select></label><div class="row">${button('govern:save-new','Save for review','class="primary"')}</div>`)}
function governanceOpenCard(id){const r=getRecord(id);if(!r)return governanceCard();return card(r.title,`<p>${escapeHtml(r.proposal||'')}</p><div class="kv"><b>Type</b><span>${escapeHtml(r.subtype)}</span><b>Consent</b><span>${escapeHtml(r.consent||'review')}</span><b>Status</b><span>${escapeHtml(r.status)}</span></div><label><span>Decision note</span><textarea data-field="decisionNote"></textarea></label><label class="row"><input data-field="confirmGovern" type="checkbox"> Apply this governance decision to local shared state.</label><div class="row">${button(`govern:approve:${id}`,'Approve','class="primary"')}${button(`govern:reject:${id}`,'Reject')}</div>`)}
function decideGovernance(id,decision,root){if(!checked(root,'confirmGovern'))throw new Error('Confirm the governance decision first.');const r=updateRecord(id,{status:decision,decisionNote:field(root,'decisionNote'),decidedAt:now()});if(r.subtype==='proposal'&&decision==='approved')draftSystemEvent('anarchadia.policy.published','anarchadia','civweave',{recordId:id,title:r.title});audit('anarchadia.record.decided',{recordId:id,decision});return r}

function recordsCard(){const all=records(),summary=validationSummary(),drafts=read(KEYS.projections,[]),inbox=read(KEYS.inbox,[]);return card('Local ledgers',`<div class="kv"><b>Learning</b><span>${all.filter(r=>r.kind==='learning').length}</span><b>Work</b><span>${all.filter(r=>r.kind==='work').length}</span><b>Market</b><span>${all.filter(r=>r.kind==='market').length}</span><b>Governance</b><span>${all.filter(r=>r.kind==='governance').length}</span><b>Validations</b><span>${validations().length}</span><b>System drafts</b><span>${drafts.length}</span><b>Handoffs</b><span>${inbox.length}</span><b>Audit events</b><span>${events().length}</span></div><small>${escapeHtml(summary.label)}</small><div class="row">${button('backup:export','Export backup')}${button('backup:import-card','Restore backup')}${button('records:clear','Clear local data','class="danger"')}</div>`)}
function backupCard(){return card('Restore backup',`<p>Restore a Civweave Chat JSON backup. Existing local state is replaced only after explicit confirmation.</p><label><span>Backup JSON</span><textarea data-field="backupJson" placeholder="Paste exported JSON"></textarea></label><label class="row"><input data-field="confirmRestore" type="checkbox"> Replace this device’s local Civweave Chat state.</label><div class="row">${button('backup:restore','Restore','class="primary"')}</div>`)}
function exportBackup(){const payload={schema:'civweave.chat.backup.v3',version:VERSION,exportedAt:now(),working:read(KEYS.working,{}),inbox:read(KEYS.inbox,[]),records:records(),validations:validations(),rewards:read(KEYS.rewards,{}),creator:creator(),peers:peers(),pairingInbox:pairingInbox(),settings:settings(),events:events(),projections:read(KEYS.projections,[]),paymentReceipts:read(KEYS.paymentReceipts,[])};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`civweave-chat-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);audit('backup.exported',{})}
function restoreBackup(root){if(!checked(root,'confirmRestore'))throw new Error('Confirm restore first.');const b=parse(field(root,'backupJson'),null);if(!b||!/^civweave\.chat\.backup\.v[23]$/.test(b.schema||''))throw new Error('Unsupported Civweave Chat backup.');write(KEYS.working,b.working||{});write(KEYS.inbox,b.inbox||[]);write(KEYS.records,b.records||[]);write(KEYS.validations,b.validations||[]);write(KEYS.rewards,b.rewards||{});write(KEYS.creator,b.creator||{});write(KEYS.peers,b.peers||[]);write(KEYS.pairingInbox,b.pairingInbox||[]);write(KEYS.settings,b.settings||{});write(KEYS.events,b.events||[]);write(KEYS.projections,b.projections||[]);write(KEYS.paymentReceipts,b.paymentReceipts||[]);return true}
