import { STRIPE_API_VERSION, STRIPE_API_KEY, CONNECT_DEFAULT_CURRENCY, hash, clean, safeCurrency, safeCountry, safeEntityType, safeAccountId, safeReference, connectReturnUrl, requestOrigin, sameOriginRequest, rateAllowed, json, readBody } from './server-common.js';

async function stripeV2(path,{method='GET',body=null,idempotencyKey=''}={}){if(!STRIPE_API_KEY)throw Object.assign(new Error('Stripe is not configured.'),{status:503});const response=await fetch(`https://api.stripe.com${path}`,{method,headers:{Authorization:`Bearer ${STRIPE_API_KEY}`,'Stripe-Version':STRIPE_API_VERSION,...(body?{'Content-Type':'application/json'}:{}),...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(clean(data?.error?.message||data?.error||'Stripe Connect request failed.',1000)),{status:response.status>=500?502:400});return data}
async function retrieveConnectedAccount(accountId){const q=new URLSearchParams();for(const field of ['configuration.recipient','requirements','defaults'])q.append('include[]',field);return stripeV2(`/v2/core/accounts/${encodeURIComponent(accountId)}?${q}`)}
function accountTransferStatus(account){return account?.configuration?.recipient?.capabilities?.stripe_balance?.stripe_transfers?.status||'pending'}
function accountBoundToCreator(account,creatorNodeId){return clean(account?.metadata?.civweave_creator_node_id,180)===creatorNodeId}
async function createConnectedAccount({creatorNodeId,displayName,contactEmail,country,entityType,currency}){return stripeV2('/v2/core/accounts',{method:'POST',idempotencyKey:`civweave-connect-${hash(creatorNodeId).slice(0,32)}`,body:{contact_email:contactEmail,display_name:displayName,dashboard:'express',identity:{country,entity_type:entityType},configuration:{recipient:{capabilities:{stripe_balance:{stripe_transfers:{requested:true}}}}},defaults:{currency:safeCurrency(currency)||CONNECT_DEFAULT_CURRENCY,responsibilities:{fees_collector:'application',losses_collector:'application'}},metadata:{civweave_creator_node_id:creatorNodeId,civweave_role:'creator'},include:['configuration.recipient','requirements','defaults']}})}
async function createAccountLink(req,accountId){return stripeV2('/v2/core/account_links',{method:'POST',body:{account:accountId,use_case:{type:'account_onboarding',account_onboarding:{configurations:['recipient'],refresh_url:connectReturnUrl(req,'refresh',accountId),return_url:connectReturnUrl(req,'return',accountId),collection_options:{fields:'eventually_due',future_requirements:'include'}}}}})}
async function validateConnectedAccount(accountId,creatorNodeId){const account=await retrieveConnectedAccount(accountId);if(!accountBoundToCreator(account,creatorNodeId))throw Object.assign(new Error('Connected account is not bound to this Creator mesh identity.'),{status:403});return account}

async function handleConnect(req,res,url){
  const appOrigin=requestOrigin(req);if(!appOrigin)return json(res,503,{error:'APP_ORIGIN is required outside localhost.'},req);if(!sameOriginRequest(req,appOrigin))return json(res,403,{error:'Origin rejected.'},req);if(!rateAllowed(req,20))return json(res,429,{error:'Too many Connect requests.'},req);
  if(url.pathname==='/api/connect/status'&&req.method==='GET'){
    if(!rateAllowed(req,60))return json(res,429,{error:'Too many Connect status requests.'},req);
    const accountId=safeAccountId(url.searchParams.get('accountId')),creatorNodeId=safeReference(url.searchParams.get('creatorNodeId'));if(!accountId||!creatorNodeId)return json(res,400,{error:'accountId and creatorNodeId are required.'},req);const account=await validateConnectedAccount(accountId,creatorNodeId),transferStatus=accountTransferStatus(account);return json(res,200,{provider:'stripe',accountId,status:transferStatus==='active'?'ready':'onboarding',ready:transferStatus==='active',transferStatus,dashboard:account.dashboard||'express'},req);
  }
  if(url.pathname==='/api/connect/onboarding'&&req.method==='POST'){
    if(!String(req.headers['content-type']||'').toLowerCase().startsWith('application/json'))return json(res,415,{error:'Expected application/json.'},req);const body=await readBody(req),creatorNodeId=safeReference(body.creatorNodeId),contactEmail=clean(body.contactEmail,254),country=safeCountry(body.country),entityType=safeEntityType(body.entityType||'individual'),displayName=clean(body.displayName||'Creator',120),currency=safeCurrency(body.currency)||CONNECT_DEFAULT_CURRENCY;if(body.schema!=='civweave.connect-onboarding-request.v1'||!creatorNodeId||!/^\S+@\S+\.\S+$/.test(contactEmail)||!country||!entityType)return json(res,400,{error:'Invalid Creator onboarding request.'},req);let account=body.accountId?await validateConnectedAccount(safeAccountId(body.accountId),creatorNodeId):null;if(!account)account=await createConnectedAccount({creatorNodeId,displayName,contactEmail,country,entityType,currency});const transferStatus=accountTransferStatus(account),link=await createAccountLink(req,account.id);if(!link?.url)return json(res,502,{error:'Stripe did not return an onboarding URL.'},req);return json(res,200,{accountId:account.id,onboardingUrl:link.url,status:transferStatus==='active'?'ready':'onboarding',ready:transferStatus==='active'},req);
  }
  return json(res,404,{error:'Not found.'},req);
}

export { handleConnect, validateConnectedAccount, accountTransferStatus };