function statePatch(patch){const s=read(KEYS.state,{}),next={...s,...patch};write(KEYS.state,next);return next}
function activeWeave(){return read(KEYS.working,{})?.plan||null}
function upsertRecord(item){const all=records(),i=all.findIndex(r=>r.id===item.id),next={...item,updatedAt:now()};if(i>=0)all[i]=next;else all.unshift(next);write(KEYS.records,all.slice(0,1500));return next}
function getRecord(id){return records().find(r=>r.id===id)||null}
function newRecord(kind,subtype,data={}){return upsertRecord({id:uid(kind),schema:'civweave.chat.record.v3',kind,subtype,status:data.status||'draft',createdAt:now(),...data})}

function buildWeave(wish,{outcome='',context='',constraints='',posture='practice',level=2}={}){
  const t=now(),plan={id:uid('weave'),schema:'civweave.chat.weave.v3',title:clean(wish,90),wish:clean(wish,1000),clarification:{outcome:clean(outcome,1200),context:clean(context,1200),constraints:clean(constraints,2000)},skill:{posture:clean(posture,40)||'practice',level:Math.max(0,Math.min(5,Number(level)||0))},state:'review',statedAt:t,clarifiedAt:t,skillAt:t,generatedAt:t,updatedAt:t,paths:{learning:`Learn what is required to make “${clean(wish,160)}” real, then demonstrate competency.`,work:`Turn “${clean(wish,160)}” into reviewable quests, deliverables and evidence.`,materials:`Find the materials, services or collaborators needed for “${clean(wish,160)}”.`,governance:'Keep consent, roles, validation rules and consequential transitions reviewable.'}};
  write(KEYS.working,{stage:'review',plan,updatedAt:t});audit('civweave.weave.generated',{weaveId:plan.id});return plan
}
function wishCard(){const p=activeWeave();if(!p)return card('Wish → weave',`<p>State the outcome, give it useful edges, then choose how much learning should be folded into the route.</p><label><span>Wish</span><textarea data-field="wish" placeholder="I want to…"></textarea></label><label><span>Visible success</span><textarea data-field="outcome" placeholder="What would count as done?"></textarea></label><label><span>Context</span><textarea data-field="context" placeholder="Who, where, what environment?"></textarea></label><label><span>Constraints / boundaries</span><textarea data-field="constraints" placeholder="Budget, time, safety, consent…"></textarea></label><div class="split"><label><span>Skill posture</span><select data-field="posture"><option value="learn">Learn first</option><option value="practice" selected>Practice while doing</option><option value="known">I already know this</option></select></label><label><span>Skill level · 0–5</span><input data-field="level" type="number" min="0" max="5" value="2"></label></div><div class="row">${button('wish:draft','Generate weave','class="primary"')}</div>`);
  return weaveSummary(p)
}
function weaveSummary(p){return card('Current weave',`<div class="row"><span class="chip ok">wish</span><span class="chip ${p.reviewedAt?'ok':'warn'}">review</span><span class="chip ${p.activatedAt?'ok':'warn'}">${escapeHtml(p.state)}</span><span class="chip ${p.passport?.sealedAt?'ok':'warn'}">passport</span></div><div class="kv"><b>Wish</b><span>${escapeHtml(p.wish)}</span><b>Success</b><span>${escapeHtml(p.clarification?.outcome||'not specified')}</span><b>Skill</b><span>${escapeHtml(p.skill?.posture||'practice')} · ${Number(p.skill?.level??2)}/5</span></div><div class="stack"><div class="creator-preview"><strong>🌰 Learning</strong><p>${escapeHtml(p.paths?.learning||'')}</p></div><div class="creator-preview"><strong>🎁 Work</strong><p>${escapeHtml(p.paths?.work||'')}</p></div><div class="creator-preview"><strong>🔘 Materials & services</strong><p>${escapeHtml(p.paths?.materials||'')}</p></div><div class="creator-preview"><strong>🧙 Governance</strong><p>${escapeHtml(p.paths?.governance||'')}</p></div></div><div class="row">${button('wish:review','Review / revise','class="primary"')}${p.activatedAt?button('wish:pause','Pause'):button('wish:activate-card','Activate')}${button('wish:passport','Passport')}${button('wish:clear','Clear','class="danger"')}</div>`)}
function reviewWeaveCard(){const p=activeWeave();if(!p)return wishCard();return card('Review weave',`<p>Revise the four handoffs before activation.</p><label><span>Living School request</span><textarea data-field="learning">${escapeHtml(p.paths.learning)}</textarea></label><label><span>Cerbanimo request</span><textarea data-field="work">${escapeHtml(p.paths.work)}</textarea></label><label><span>FellowFare request</span><textarea data-field="materials">${escapeHtml(p.paths.materials)}</textarea></label><label><span>Anarchadia record</span><textarea data-field="governance">${escapeHtml(p.paths.governance)}</textarea></label><div class="row">${button('wish:save-review','Save reviewed weave','class="primary"')}</div>`)}
function saveWeaveReview(root){const s=read(KEYS.working,{}),p=s.plan;if(!p)throw new Error('No weave to review.');p.paths={learning:field(root,'learning'),work:field(root,'work'),materials:field(root,'materials'),governance:field(root,'governance')};p.reviewedAt=now();p.updatedAt=now();write(KEYS.working,{...s,plan:p,updatedAt:now()});audit('civweave.weave.reviewed',{weaveId:p.id});return p}
function activateWeaveCard(){const p=activeWeave();if(!p)return wishCard();return card('Activate reviewed weave',`<p>${escapeHtml(p.title)}</p><label class="row"><input data-field="confirmActivate" type="checkbox"> I approve staging the learning, work, materials and governance handoffs.</label><div class="row">${button('wish:activate','Activate weave','class="primary"')}</div><small>Activation stages records. It does not spend money, publish externally, or submit work.</small>`)}
function activateWeave(){const s=read(KEYS.working,{}),p=s.plan;if(!p)throw new Error('No weave to activate.');if(!p.reviewedAt)p.reviewedAt=now();p.state='active';p.activatedAt=now();p.updatedAt=now();write(KEYS.working,{...s,stage:'active',plan:p,updatedAt:now()});
  const existing=records().filter(r=>r.weaveId===p.id);
  if(!existing.some(r=>r.subtype==='learning-path'))newRecord('learning','learning-path',{weaveId:p.id,title:`Learning · ${p.title}`,goal:p.paths.learning,status:'ready',modules:[]});
  if(!existing.some(r=>r.subtype==='work-quest'))newRecord('work','work-quest',{weaveId:p.id,title:`Quest · ${p.title}`,deliverable:p.paths.work,evidence:'',status:'queued'});
  if(!existing.some(r=>r.subtype==='market-thread'))newRecord('market','market-thread',{weaveId:p.id,title:`Need · ${p.title}`,needOrOffer:p.paths.materials,terms:'',amount:0,currency:settings().currency,status:'open'});
  if(!existing.some(r=>r.subtype==='governance-record'))newRecord('governance','governance-record',{weaveId:p.id,title:`Governance · ${p.title}`,proposal:p.paths.governance,consent:'review',status:'review'});
  const inbox=read(KEYS.inbox,[]);for(const target of ['living-school','cerbanimo','fellowfare','anarchadia'])inbox.unshift({id:uid('handoff'),schema:'civweave.chat.handoff.v1',target,status:'review',createdAt:now(),payload:{weaveId:p.id,wish:p.wish}});write(KEYS.inbox,inbox.slice(0,300));audit('civweave.weave.activated',{weaveId:p.id});return p
}
function passportCard(){const p=activeWeave();if(!p)return card('Passport','<p>Create a weave first.</p>');return card('Anarchadia Passport',`<p>${escapeHtml(p.wish)}</p><label><span>Personal pledge</span><textarea data-field="pledge">${escapeHtml(p.passport?.pledge||'I will keep this intention revisable, respect consent, and record what changes.')}</textarea></label><label class="row"><input data-field="confirmPassport" type="checkbox"> I choose to seal this intention in my local Passport.</label><div class="row">${button('passport:seal','Seal intention','class="primary"')}</div>`)}

function journeyProgress(){const p=activeWeave(),s=read(KEYS.state,{}),all=records();const learning=all.filter(r=>r.kind==='learning'),work=all.filter(r=>r.kind==='work'),market=all.filter(r=>r.kind==='market');const checks={
  'civweave.model-setup':Boolean(s.modelSetupAt||settings().localEndpoint),
  'civweave.state-wish':Boolean(p?.wish),'civweave.clarify-wish':Boolean(p?.clarifiedAt),'civweave.skill-posture':Boolean(p?.skillAt),
  'civweave.generate-weave':Boolean(p?.generatedAt),'civweave.review-weave':Boolean(p?.reviewedAt),'civweave.activate-weave':Boolean(p?.activatedAt),
  'living-school.start-path':learning.some(r=>r.subtype==='learning-path'&&['active','complete'].includes(r.status)),
  'living-school.follow-modules':learning.some(r=>r.subtype==='learning-path'&&(r.modules||[]).some(m=>m.status==='complete')),
  'living-school.send-quest':learning.some(r=>r.questSentAt), 'cerbanimo.manage-quests':work.some(r=>r.subtype==='work-quest'&&r.managedAt),
  'cerbanimo.submit-work':work.some(r=>r.submittedAt), 'cerbanimo.settle-reward':work.some(r=>r.rewardSettledAt),
  'fellowfare.browse-threads':Boolean(s.marketBrowsedAt), 'fellowfare.accept-agreement':market.some(r=>r.subtype==='agreement'&&r.acceptedAt),
  'fellowfare.settle-exchange':market.some(r=>r.subtype==='agreement'&&r.settledAt), 'civweave.reward-wallet':Boolean(s.rewardWalletViewedAt)
};return JOURNEY.map(([id,label,tool])=>({id,label,tool,done:Boolean(checks[id])}))}
function journeyCard(){const rows=journeyProgress(),done=rows.filter(x=>x.done).length,next=rows.find(x=>!x.done);return card('Golden path',`<div class="progress"><span style="width:${Math.round(done/rows.length*100)}%"></span></div><p><strong>${done}/${rows.length}</strong> canonical steps complete.</p><div class="stack">${rows.map((x,i)=>`<div class="journey-row"><span class="chip ${x.done?'ok':'warn'}">${x.done?'✓':i+1}</span><span>${escapeHtml(x.label)}</span><small>${escapeHtml(x.id)}</small></div>`).join('')}</div>${next?`<div class="row">${button(`tool:${next.tool}`,'Continue · '+next.label,'class="primary"')}</div>`:'<p class="success">Golden path complete.</p>'}`)}
function parityCard(){const j=journeyProgress(),done=j.filter(x=>x.done).length;return card('MVP parity',`<p><strong>${done}/${JOURNEY.length}</strong> golden-path operations currently exercised in this local workspace.</p><div class="stack">${Object.entries(SYSTEMS).map(([id,s])=>`<div class="creator-preview"><strong>${escapeHtml(id)} · ${GUIDES[s.guide].emoji} ${GUIDES[s.guide].name}</strong><p>${s.families.map(escapeHtml).join(' · ')}</p></div>`).join('')}</div><small>This chat build deliberately collapses rooms into shared adapters. Visual-room parity is out of scope; state, consent, handoff, validation, reward, peer and exchange workflows are the parity target.</small>`)}
